// This file should be kept in sync with the generated output from xunit.v3.msbuildtasks

namespace Xunit.AutoGenerated
{
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	internal class XunitAutoGeneratedEntryPoint
	{
		public static int Main(string[] args)
		{
#if USE_MICROSOFT_TESTING_PLATFORM_RUNNER
			// Microsoft.Testing.Platform native UX
			if (global::System.Linq.Enumerable.Any(args, arg => arg == "-automated" || arg == "@@"))
				return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
			else
				return global::Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.RunAsync(args, SelfRegisteredExtensions.AddSelfRegisteredExtensions).GetAwaiter().GetResult();
#else
			// xUnit.net native UX
			if (global::System.Linq.Enumerable.Any(args, arg => arg == "--server" || arg == "--internal-msbuild-node"))
				return global::Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.RunAsync(args, SelfRegisteredExtensions.AddSelfRegisteredExtensions).GetAwaiter().GetResult();
			else
				return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
#endif
		}
	}
}
