// This file is identical to the auto-generated entrypoint that normally comes in via
// MSBuild from the NuGet package. See: $/src/xunit.v3.core/Package/content/AutoGeneratedEntryPoint.cs

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public class AutoGeneratedEntryPoint
{
	public static int Main(string[] args)
	{
		return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
	}
}
