// This file is similar to the auto-generated entrypoint, except that we also add an
// explicit reference to the TD.NET runner, since that would normally come in via
// the NuGet package and a .tdnet file.

[assembly: global::TestDriven.Framework.CustomTestRunner(typeof(global::Xunit.Runner.TdNet.TdNetRunner))]

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public class AutoGeneratedEntryPoint
{
	public static async global::System.Threading.Tasks.Task<int> Main(string[] args) =>
		await global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args);
}
