// This file is similar to the auto-generated entrypoint, except that we also add an
// explicit reference to the TD.NET runner, since that would normally come in via
// the NuGet package and a .tdnet file.

using TestDriven.Framework;
using Xunit.Runner.InProc.SystemConsole;

[assembly: CustomTestRunner(typeof(Xunit.Runner.TdNet.TdNetRunner))]

public class AutoGeneratedEntryPoint
{
	public static int Main(string[] args) =>
		ConsoleRunner.Run(args).GetAwaiter().GetResult();
}
