using Xunit;
using Xunit.Generators;

public class AssemblyFixtureAttributeOfTGeneratorTests : CoreGeneratorTest<AssemblyFixtureAttributeOfTGenerator>
{
	[Fact]
	public void AcceptanceTest()
	{
		var source = /* lang=c#-test */ """
			using Xunit;
			using MyNamespace;

			// Success cases
			[assembly: AssemblyFixture<object>]
			[assembly: AssemblyFixture<MyFixture>]
			// Failure cases
			[assembly: AssemblyFixture<string>]  // No public parameterless ctor

			namespace MyNamespace {
				public class MyFixture { }
			}
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.AssemblyFixtureAttributeOfT٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal class AssemblyFixtureAttributeOfT٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyFixtureFactory(typeof(object), async () => new object());
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyFixtureFactory(typeof(global::MyNamespace.MyFixture), async () => new global::MyNamespace.MyFixture());
					}
				}
			}
			""", result);
	}
}
