using Xunit;
using Xunit.Generators;

public class CaptureConsoleAttributeGeneratorTests : CoreGeneratorTest<CaptureConsoleAttributeGenerator>
{
	[Fact]
	public void AcceptanceTest()
	{
		var source = /* lang=c#-test */ """
			using Xunit;

			[assembly: CaptureConsole]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.CaptureConsoleAttribute٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class CaptureConsoleAttribute٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyFixtureFactory(typeof(global::Xunit.CaptureConsoleAttribute.CaptureConsoleImpl), async () => new global::Xunit.CaptureConsoleAttribute.CaptureConsoleImpl());
					}
				}
			}
			""", result);
	}
}
