using Xunit;
using Xunit.Generators;

public class ClassDataAttributeOfTGeneratorTests : CoreGeneratorTest<ClassDataAttributeOfTGenerator>
{
	[Fact]
	public void AcceptanceTest()
	{
		var source = /* lang=c#-test */ """
			using System.Collections;
			using System.Collections.Generic;
			using System.Threading;
			using System.Threading.Tasks;
			using Xunit;

			public class TestClass {
			    // Success cases
				[ClassData<MyClassData>]
				[ClassData<ClassDataWithInit>(DisableParallelization = true, Skip = "Maybe?", SkipWhen = nameof(ClassDataWithInit.AlwaysFalse), SkipType = typeof(ClassDataWithInit), TestDisplayName = "hey")]
				[ClassData<AsyncClassData>(Explicit = true, Label = "hello", Skip = "Always", SkipUnless = nameof(AlwaysTrue), Timeout = 42, Traits = ["Foo", "Bar"])]
				// Failure cases
				[ClassData<NonEnumerableData>]
				[ClassData<PrivateInnerClass>]
				[ClassData<AbstractClass>]
				[ClassData<MissingCtor>]
				[ClassData<WrongDataType>]
				[ClassData<MyClassData>(Skip = "ohno", SkipUnless = nameof(AlwaysTrue), SkipWhen = nameof(AlwaysTrue))]  // Can't set both
				[ClassData<MyClassData>(Skip = "ohno", SkipUnless = nameof(AlwaysTruthy))]  // Wrong return type
				[ClassData<MyClassData>(Skip = "ohno", SkipWhen = nameof(AlwaysTruthy))]  // Wrong return type
				public void TestMethod(int _1, string _2) { }

				public static bool AlwaysTrue => true;
				public static string AlwaysTruthy => "yes";

				class PrivateInnerClass : List<object[]> { }
			}

			public class MyClassData() : List<object[]>(new[] { new object[] { 42, "Hello world" } }) { }

			public class ClassDataWithInit : IEnumerable<object[]>, IAsyncLifetime {
				public ValueTask InitializeAsync() => default;
				public ValueTask DisposeAsync() => default;
				public IEnumerator<object[]> GetEnumerator() {
					yield return [42, "Hello world"];
				}

				IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

				public static bool AlwaysFalse => false;
			}

			public class AsyncClassData : IAsyncEnumerable<object[]> {
				public async IAsyncEnumerator<object[]> GetAsyncEnumerator(CancellationToken cancellationToken = default) {
					await Task.Delay(0);
					yield return [42, "Hello world"];
				}
			}

			public class NonEnumerableData { }
			public abstract class AbstractClass : List<object[]> { }
			public class MissingCtor(int capacity) : List<object[]>(capacity) { }
			public class WrongDataType : List<string> { }
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.ClassDataAttributeOfT٠TestClass٠TestMethod٠EJcNgMSMN]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class ClassDataAttributeOfT٠TestClass٠TestMethod٠EJcNgMSMN : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", false,
							async disposalTracker => {
								var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
								var dataRows = new global::System.Collections.Generic.List<global::Xunit.ITheoryDataRow>();
								var classData = new global::MyClassData();
								disposalTracker.Add(classData);
								foreach (var dataRow in classData)
									dataRows.Add(attr.CreateDataRow(dataRow));
								return dataRows;
							}
						);
						global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", false,
							async disposalTracker => {
								var attr = new global::Xunit.v3.DataAttributeRegistration() { DisableParallelization = true, Skip = "Maybe?", SkipWhen = () => global::ClassDataWithInit.AlwaysFalse, TestDisplayName = "hey" };
								var dataRows = new global::System.Collections.Generic.List<global::Xunit.ITheoryDataRow>();
								var classData = new global::ClassDataWithInit();
								disposalTracker.Add(classData);
								await ((global::Xunit.IAsyncLifetime)classData).InitializeAsync();
								foreach (var dataRow in classData)
									dataRows.Add(attr.CreateDataRow(dataRow));
								return dataRows;
							}
						);
						global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", false,
							async disposalTracker => {
								var attr = new global::Xunit.v3.DataAttributeRegistration() { Explicit = true, Label = "hello", Skip = "Always", SkipUnless = () => global::TestClass.AlwaysTrue, Timeout = 42, Traits = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.IReadOnlyCollection<string>>(global::System.StringComparer.OrdinalIgnoreCase) { ["Foo"] = new global::System.Collections.Generic.HashSet<string> { "Bar" }} };
								var dataRows = new global::System.Collections.Generic.List<global::Xunit.ITheoryDataRow>();
								var classData = new global::AsyncClassData();
								disposalTracker.Add(classData);
								await foreach (var dataRow in classData)
									dataRows.Add(attr.CreateDataRow(dataRow));
								return dataRows;
							}
						);
					}
				}
			}
			""", result);
	}
}
