using Xunit;
using Xunit.Generators;

public class CollectionBehaviorAttributeOfTGeneratorTests : CoreGeneratorTest<CollectionBehaviorAttributeOfTGenerator>
{
	[Fact]
	public void SuccessCase()
	{
		var source = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[assembly: CollectionBehavior<CollectionPerAssemblyTestCollectionFactory>]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.CollectionBehaviorAttributeOfT٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class CollectionBehaviorAttributeOfT٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterTestCollectionFactoryFactory((assembly) => new global::Xunit.v3.CollectionPerAssemblyTestCollectionFactory(assembly));
					}
				}
			}
			""", result);
	}

	[Fact]
	public void FailureCase()
	{
		var source = /* lang=c#-test */ """
			using System;
			using Xunit;
			using Xunit.v3;

			// Missing constructor with ICodeGenTestAssembly
			[assembly: CollectionBehavior<MyTestCollectionFactory>]

			public class MyTestCollectionFactory : ICodeGenTestCollectionFactory {
				public string DisplayName => "My Test Collection Factory";
				public ICodeGenTestCollection Get(Type testClass) => throw new NotImplementedException();
			}
			""";

		var result = GenerateSources(source);

		Assert.Empty(result);
	}
}
