using Xunit;
using Xunit.Generators;

public class CollectionDefinitionAttributeGeneratorTests : CoreGeneratorTest<CollectionDefinitionAttributeGenerator>
{
	[Fact]
	public void AcceptanceTest()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using System;
			using System.Collections.Generic;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			// Success cases

			[CollectionDefinition]
			public class CollectionByType { }

			[CollectionDefinition("Collection name")]
			public class CollectionByName { }

			[CollectionDefinition(DisableParallelization = true)]
			public class WithParameters { }

			[CollectionDefinition]
			[TestCaseOrderer(typeof(UnorderedTestCaseOrderer))]
			[TestClassOrderer(typeof(UnorderedTestClassOrderer))]
			[TestMethodOrderer(typeof(UnorderedTestMethodOrderer))]
			public class WithOrderers_NonGeneric { }

			[CollectionDefinition]
			[TestCaseOrderer<MyOrderer>]
			[TestClassOrderer<MyOrderer>]
			[TestMethodOrderer<MyOrderer>]
			public class WithOrderers_Generic { }

			[CollectionDefinition]
			public class WithFixtures : ICollectionFixture<object>, IClassFixture<TypeWithDependency>, IClassFixture<TypeWithMarkerInterface> { }

			// Failure cases

			[CollectionDefinition]  // Open generics not supported
			public class OpenGenericType<T> { }

			public class TypeWithDependency(object x) { public override string ToString() => x.ToString()!; }

			public class TypeWithMarkerInterface : INotifyLifecycle { }

			public class MyOrderer : ITestCaseOrderer, ITestClassOrderer, ITestMethodOrderer
			{
				public IReadOnlyCollection<TTestCase> OrderTestCases<TTestCase>(IReadOnlyCollection<TTestCase> testCases)
					where TTestCase : notnull, ITestCase =>
						throw new NotImplementedException();
				public IReadOnlyCollection<TTestClass?> OrderTestClasses<TTestClass>(IReadOnlyCollection<TTestClass?> testClasses)
					where TTestClass : notnull, ITestClass =>
						throw new NotImplementedException();
				public IReadOnlyCollection<TTestMethod?> OrderTestMethods<TTestMethod>(IReadOnlyCollection<TTestMethod?> testMethods)
					where TTestMethod : notnull, ITestMethod =>
						throw new NotImplementedException();
			}
			""";

		var result = GenerateSources(source);

		Assert.Collection(
			result,
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.CollectionDefinitionAttribute٠CollectionByType٠m2q3zYbjH]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class CollectionDefinitionAttribute٠CollectionByType٠m2q3zYbjH : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCollectionDefinition(null, new global::Xunit.v3.CodeGenTestCollectionRegistration() { Type = typeof(global::CollectionByType) });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.CollectionDefinitionAttribute٠CollectionByName٠dh7o6QAtQ]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class CollectionDefinitionAttribute٠CollectionByName٠dh7o6QAtQ : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCollectionDefinition("Collection name", new global::Xunit.v3.CodeGenTestCollectionRegistration() { Type = typeof(global::CollectionByName) });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.CollectionDefinitionAttribute٠WithParameters٠4ywMzzjFE]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class CollectionDefinitionAttribute٠WithParameters٠4ywMzzjFE : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCollectionDefinition(null, new global::Xunit.v3.CodeGenTestCollectionRegistration() { DisableParallelization = true, Type = typeof(global::WithParameters) });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.CollectionDefinitionAttribute٠WithOrderers_NonGeneric٠6Om8k3xmX]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class CollectionDefinitionAttribute٠WithOrderers_NonGeneric٠6Om8k3xmX : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCollectionDefinition(null, new global::Xunit.v3.CodeGenTestCollectionRegistration() { TestCaseOrdererFactory = () => global::Xunit.v3.UnorderedTestCaseOrderer.Instance, TestClassOrdererFactory = () => global::Xunit.v3.UnorderedTestClassOrderer.Instance, TestMethodOrdererFactory = () => global::Xunit.v3.UnorderedTestMethodOrderer.Instance, Type = typeof(global::WithOrderers_NonGeneric) });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.CollectionDefinitionAttribute٠WithOrderers_Generic٠oiNnzRLP3]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class CollectionDefinitionAttribute٠WithOrderers_Generic٠oiNnzRLP3 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCollectionDefinition(null, new global::Xunit.v3.CodeGenTestCollectionRegistration() { TestCaseOrdererFactory = () => new global::MyOrderer(), TestClassOrdererFactory = () => new global::MyOrderer(), TestMethodOrdererFactory = () => new global::MyOrderer(), Type = typeof(global::WithOrderers_Generic) });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.CollectionDefinitionAttribute٠WithFixtures٠LiTahwpXa]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class CollectionDefinitionAttribute٠WithFixtures٠LiTahwpXa : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCollectionDefinition(null, new global::Xunit.v3.CodeGenTestCollectionRegistration() { ClassFixtureFactories = new global::System.Collections.Generic.Dictionary<global::System.Type, global::Xunit.v3.FixtureFactory> {
								[typeof(global::TypeWithDependency)] = async (mappingManager, forceCreation) => {
									if (!forceCreation)
										return null;
									var missingParameters = new global::System.Collections.Generic.List<(string Type, string Name)>();
									var param0 = await global::Xunit.v3.FixtureMappingManager.TryGetFixtureArgument<object>(mappingManager);
									if (!param0.Success)
										missingParameters.Add(("object", "x"));
									if (missingParameters.Count != 0)
										throw new global::Xunit.Sdk.TestPipelineException(
											string.Format(
												global::System.Globalization.CultureInfo.CurrentCulture,
												"Class fixture type 'TypeWithDependency' had one or more unresolved constructor arguments: {0}",
												string.Join(", ", global::System.Linq.Enumerable.Select(missingParameters, p => $"{p.Type} {p.Name}"))
											)
										);
									var instance = new global::TypeWithDependency(param0.Result!);
									return instance;
								}, [typeof(global::TypeWithMarkerInterface)] = async (mappingManager, forceCreation) => {
									var instance = new global::TypeWithMarkerInterface();
									return instance;
								}
							}, CollectionFixtureFactories = new global::System.Collections.Generic.Dictionary<global::System.Type, global::Xunit.v3.FixtureFactory> {
								[typeof(object)] = async (mappingManager, forceCreation) => {
									if (!forceCreation)
										return null;
									var instance = new object();
									return instance;
								}
							}, Type = typeof(global::WithFixtures) });
						}
					}
				}
				""", generated)
		);
	}

	[Fact]
	public void Partials()
	{
		var source1 = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[TestCaseOrderer(typeof(DefaultTestCaseOrderer))]
			[CollectionDefinition("foo")]
			public partial class CollectionDefinition { }
			""";
		var source2 = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[TestClassOrderer(typeof(DefaultTestClassOrderer))]
			partial class CollectionDefinition { }
			""";

		var generated = GenerateSingleSource(source1, source2);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.CollectionDefinitionAttribute٠CollectionDefinition٠uG73qQHC4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class CollectionDefinitionAttribute٠CollectionDefinition٠uG73qQHC4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterCollectionDefinition("foo", new global::Xunit.v3.CodeGenTestCollectionRegistration() { TestCaseOrdererFactory = () => global::Xunit.v3.DefaultTestCaseOrderer.Instance, TestClassOrdererFactory = () => global::Xunit.v3.DefaultTestClassOrderer.Instance, Type = typeof(global::CollectionDefinition) });
					}
				}
			}
			""", generated);
	}
}
