using Xunit;
using Xunit.Generators;

public class InlineDataAttributeGeneratorTests : CoreGeneratorTest<InlineDataAttributeGenerator>
{
	[Fact]
	public void AcceptanceTest()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using Xunit;

			public class TestClass {
				[Theory]
				// Success cases
				[InlineData]
				[InlineData(null, DisableParallelization = true, Skip = "Maybe?", SkipWhen = nameof(OtherClass.AlwaysFalse), SkipType = typeof(OtherClass), TestDisplayName = "hey")]
				[InlineData("Hello", 2112, Explicit = true, Label = "hello", Skip = "Always", SkipUnless = nameof(AlwaysTrue), Timeout = 42, Traits = ["Foo", "Bar"])]
				// Failure cases
				[InlineData(Skip = "ohno", SkipUnless = nameof(AlwaysTrue), SkipWhen = nameof(AlwaysTrue))]  // Can't set both
				[InlineData(Skip = "ohno", SkipUnless = nameof(AlwaysTruthy))]  // Wrong return type
				[InlineData(Skip = "ohno", SkipWhen = nameof(AlwaysTruthy))]  // Wrong return type
				public void TestMethod(string? _1 = null, int _2 = 42) { }

				public static bool AlwaysTrue => true;
				public static string AlwaysTruthy => "yes";
			}

			public abstract class GenericClass<T1, T2> {
				[Theory]
				[InlineData(42)]
				public void TestMethod(int _) { }
			}

			public class OtherClass {
				public static bool AlwaysFalse => false;
			}

			public class TypeOfMultiDimensionalArray {
				[Theory]
				[InlineData(typeof(int[,]))]
				public void TestMethod(object o) { }
			}
			""";

		var result = GenerateSources(source);

		Assert.Collection(
			result,
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.InlineDataAttribute٠TestClass٠TestMethod٠4tTPAmvà2]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class InlineDataAttribute٠TestClass٠TestMethod٠4tTPAmvà2 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", false,
								async disposalTracker => {
									var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
									var data = new object?[] {  };
									return new[] { attr.CreateDataRow(data) };
								}
							);
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", false,
								async disposalTracker => {
									var attr = new global::Xunit.v3.DataAttributeRegistration() { DisableParallelization = true, Skip = "Maybe?", SkipWhen = () => global::OtherClass.AlwaysFalse, TestDisplayName = "hey" };
									var data = new object?[] { null };
									return new[] { attr.CreateDataRow(data) };
								}
							);
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", false,
								async disposalTracker => {
									var attr = new global::Xunit.v3.DataAttributeRegistration() { Explicit = true, Label = "hello", Skip = "Always", SkipUnless = () => global::TestClass.AlwaysTrue, Timeout = 42, Traits = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.IReadOnlyCollection<string>>(global::System.StringComparer.OrdinalIgnoreCase) { ["Foo"] = new global::System.Collections.Generic.HashSet<string> { "Bar" }} };
									var data = new object?[] { "Hello", 2112 };
									return new[] { attr.CreateDataRow(data) };
								}
							);
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.InlineDataAttribute٠GenericClass٠TestMethod٠Z9mskHrKn]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class InlineDataAttribute٠GenericClass٠TestMethod٠Z9mskHrKn : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::GenericClass<,>", "TestMethod", false,
								async disposalTracker => {
									var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
									var data = new object?[] { 42 };
									return new[] { attr.CreateDataRow(data) };
								}
							);
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.InlineDataAttribute٠TypeOfMultiDimensionalArray٠TestMethod٠jRIáe4BnF]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class InlineDataAttribute٠TypeOfMultiDimensionalArray٠TestMethod٠jRIáe4BnF : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TypeOfMultiDimensionalArray", "TestMethod", false,
								async disposalTracker => {
									var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
									var data = new object?[] { typeof(int[,]) };
									return new[] { attr.CreateDataRow(data) };
								}
							);
						}
					}
				}
				""", generated)
		);
	}
}
