using Xunit;
using Xunit.Generators;

public class InlineDataAttributeGeneratorTests : CoreGeneratorTest<InlineDataAttributeGenerator>
{
	[Fact]
	public void AcceptanceTest()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using Xunit;

			public class TestClass {
				[Theory]
				// Success cases
				[InlineData]
				[InlineData(null, DisableParallelization = true, Skip = "Maybe?", SkipWhen = nameof(OtherClass.AlwaysFalse), SkipType = typeof(OtherClass), TestDisplayName = "hey")]
				[InlineData("Hello\u0085𐱃", 2112, Explicit = true, Label = "hello", Skip = "Always", SkipUnless = nameof(AlwaysTrue), Timeout = 42, Traits = ["Foo", "Bar"])]
				// Failure cases
				[InlineData(Skip = "ohno", SkipUnless = nameof(AlwaysTrue), SkipWhen = nameof(AlwaysTrue))]  // Can't set both
				[InlineData(Skip = "ohno", SkipUnless = nameof(AlwaysTruthy))]  // Wrong return type
				[InlineData(Skip = "ohno", SkipWhen = nameof(AlwaysTruthy))]  // Wrong return type
				public void TestMethod(string? _1 = null, int _2 = 42) { }

				public static bool AlwaysTrue => true;
				public static string AlwaysTruthy => "yes";
			}

			public abstract class GenericClass<T1, T2> {
				[Theory]
				[InlineData(42)]
				public void TestMethod(int _) { }
			}

			public class OtherClass {
				public static bool AlwaysFalse => false;
			}

			public class TypeOfMultiDimensionalArray {
				[Theory]
				[InlineData(typeof(int[,]))]
				public void TestMethod(object o) { }
			}
			""";

		var result = GenerateSources(source);

		Assert.Collection(
			result,
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#if XUNIT_GENERATED_DISABLE_WARNINGS
				#pragma warning disable
				#endif

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.InlineDataAttribute٠TestClass٠TestMethod٠4tTPAmvà2]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class InlineDataAttribute٠TestClass٠TestMethod٠4tTPAmvà2 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", false,
								async disposalTracker => {
									var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
									var data = new object?[] {  };
									return new[] { attr.CreateDataRow(data) };
								}
							);
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", false,
								async disposalTracker => {
									var attr = new global::Xunit.v3.DataAttributeRegistration() { DisableParallelization = true, Skip = "Maybe?", SkipWhen = () => global::OtherClass.AlwaysFalse, TestDisplayName = "hey" };
									var data = new object?[] { null };
									return new[] { attr.CreateDataRow(data) };
								}
							);
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", false,
								async disposalTracker => {
									var attr = new global::Xunit.v3.DataAttributeRegistration() { Explicit = true, Label = "hello", Skip = "Always", SkipUnless = () => global::TestClass.AlwaysTrue, Timeout = 42, Traits = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.IReadOnlyCollection<string>>(global::System.StringComparer.OrdinalIgnoreCase) { ["Foo"] = new global::System.Collections.Generic.HashSet<string> { "Bar" }} };
									var data = new object?[] { "Hello\u0085\uD803\uDC43", 2112 };
									return new[] { attr.CreateDataRow(data) };
								}
							);
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#if XUNIT_GENERATED_DISABLE_WARNINGS
				#pragma warning disable
				#endif

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.InlineDataAttribute٠GenericClass٠TestMethod٠4aGGjtnVX]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class InlineDataAttribute٠GenericClass٠TestMethod٠4aGGjtnVX : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::GenericClass<,>", "TestMethod", false,
								async disposalTracker => {
									var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
									var data = new object?[] { 42 };
									return new[] { attr.CreateDataRow(data) };
								}
							);
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#if XUNIT_GENERATED_DISABLE_WARNINGS
				#pragma warning disable
				#endif

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.InlineDataAttribute٠TypeOfMultiDimensionalArray٠TestMethod٠iDMxLM1rj]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class InlineDataAttribute٠TypeOfMultiDimensionalArray٠TestMethod٠iDMxLM1rj : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TypeOfMultiDimensionalArray", "TestMethod", false,
								async disposalTracker => {
									var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
									var data = new object?[] { typeof(int[,]) };
									return new[] { attr.CreateDataRow(data) };
								}
							);
						}
					}
				}
				""", generated)
		);
	}

	[Fact]
	public void BaseClassInReferencedAssembly()
	{
		var referencedSource = /* lang=c#-test */ """
			using Xunit;

			namespace Contracts;

			public abstract class ContractTestsBase
			{
				[Theory]
				[InlineData(1)]
				public void BaseTheory(int _) { }
			}

			public abstract class ContractTests : ContractTestsBase
			{
				[Theory]
				[InlineData(42, Skip = "Not yet")]
				[InlineData(2112)]
				public void ContractTheory(int _) { }

				[Fact]
				public void ContractFact() { }
			}

			public abstract class GenericContractTests<T>
			{
				[Theory]
				[InlineData("hello")]
				public void GenericContractTheory(string _) { }
			}
			""";
		var source = /* lang=c#-test */ """
			public class FooTests : Contracts.ContractTests;

			// Registration is per declaring type, so this must not generate duplicates
			public class BarTests : Contracts.ContractTests;

			public class BazTests : Contracts.GenericContractTests<int>;
			""";

		var result = GenerateSourcesWithReferencedAssembly(referencedSource, source);

		string GetRegistration(string typeIndex, string methodName) =>
			Assert.Single(result, r => r.Contains($"RegisterTheoryDataRowFactory(\"{typeIndex}\", \"{methodName}\""));

		Assert.Equal(3, result.Length);
		Assert.Contains(/* lang=c#-test */ """
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::Contracts.ContractTests", "ContractTheory", false,
								async disposalTracker => {
									var attr = new global::Xunit.v3.DataAttributeRegistration() { Skip = "Not yet" };
									var data = new object?[] { 42 };
									return new[] { attr.CreateDataRow(data) };
								}
							);
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::Contracts.ContractTests", "ContractTheory", false,
								async disposalTracker => {
									var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
									var data = new object?[] { 2112 };
									return new[] { attr.CreateDataRow(data) };
								}
							);
						}
				""", GetRegistration("global::Contracts.ContractTests", "ContractTheory"));
		Assert.Contains(/* lang=c#-test */ """
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::Contracts.ContractTestsBase", "BaseTheory", false,
								async disposalTracker => {
									var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
									var data = new object?[] { 1 };
									return new[] { attr.CreateDataRow(data) };
								}
							);
						}
				""", GetRegistration("global::Contracts.ContractTestsBase", "BaseTheory"));
		Assert.Contains(/* lang=c#-test */ """
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::Contracts.GenericContractTests<>", "GenericContractTheory", false,
								async disposalTracker => {
									var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
									var data = new object?[] { "hello" };
									return new[] { attr.CreateDataRow(data) };
								}
							);
						}
				""", GetRegistration("global::Contracts.GenericContractTests<>", "GenericContractTheory"));
	}
}
