using Xunit;
using Xunit.Generators;

public class MemberDataAttributeGeneratorTests : CoreGeneratorTest<MemberDataAttributeGenerator>
{
	[Fact]
	public void AcceptanceTest()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using System.Collections;
			using System.Collections.Generic;
			using System.Threading;
			using System.Threading.Tasks;
			using Xunit;

			public class TestClass {
			    // Success cases
				[MemberData(nameof(FieldData), DisableDiscoveryEnumeration = true)]
				[MemberData(nameof(OtherClass.PropertyData), MemberType = typeof(OtherClass), DisableParallelization = true, Skip = "Maybe?", SkipWhen = nameof(OtherClass.AlwaysFalse), SkipType = typeof(OtherClass), TestDisplayName = "hey")]
				[MemberData(nameof(MethodData), 42, Explicit = true, Label = "hello", Skip = "Always", SkipUnless = nameof(AlwaysTrue), Timeout = 42, Traits = ["Foo", "Bar"])]
				// Failure cases
				[MemberData("foo")]  // Member not found
				[MemberData(nameof(Overloaded))]  // Overloaded members not supported in Native AOT
				[MemberData(nameof(WrongType))]  // Does not return theory data compatible enumeration
				[MemberData(nameof(PrivateFieldData))]  // Non-public/internal
				[MemberData(nameof(NonStaticFieldData))]  // Must be static
				[MemberData(nameof(FieldData), 42)]  // Parameters not supported on non-methods
				[MemberData(nameof(MethodData))]  // Not enough parameters
				[MemberData(nameof(MethodData), 42, "Hello", "world")]  // Too many parameters
				[MemberData(nameof(FieldData), Skip = "ohno", SkipUnless = nameof(AlwaysTrue), SkipWhen = nameof(AlwaysTrue))]  // Can't set both
				[MemberData(nameof(FieldData), Skip = "ohno", SkipUnless = nameof(AlwaysTruthy))]  // Wrong return type
				[MemberData(nameof(FieldData), Skip = "ohno", SkipWhen = nameof(AlwaysTruthy))]  // Wrong return type
				public void TestMethod(int _1, string _2) { }

				public static bool AlwaysTrue => true;
				public static string AlwaysTruthy => "yes";

				public static ValueTask<IEnumerable<object[]>> FieldData = new(new[] { new object[] { 42, "Hello world" } });
				public static async IAsyncEnumerable<(int, string)> MethodData(int x, string? y = null) {
					await Task.Yield();
					yield return (x, y ?? "Hello world");
				}
				public static TheoryData<int, string> Overloaded() => new();
				public static TheoryData<int, string> Overloaded(int _) => new();
				public static IEnumerable<string> WrongType => ["Hello world"];
				static IEnumerable<object[]> PrivateFieldData = new[] { new object[] { 42, "Hello world" } };
				public IEnumerable<object[]> NonStaticFieldData = new[] { new object[] { 42, "Hello world" } };
			}

			public class OtherClass {
				public static Task<IEnumerable<TheoryDataRow<int, string>>> PropertyData => Task.FromResult<IEnumerable<TheoryDataRow<int, string>>>([new(42, "Hello world")]);

				public static bool AlwaysFalse => false;
			}
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.MemberDataAttribute٠TestClass٠TestMethod٠8nVjyLp5O]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class MemberDataAttribute٠TestClass٠TestMethod٠8nVjyLp5O : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", true,
							async disposalTracker => {
								var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
								var result = new global::System.Collections.Generic.List<global::Xunit.ITheoryDataRow>();
								var dataRows = await global::TestClass.FieldData;
								if (dataRows == null)
									throw new global::Xunit.Sdk.TestPipelineException("Test data returned null for TestClass.TestMethod. Make sure it is statically initialized before this test method is called.");
								foreach (var dataRow in dataRows)
									result.Add(attr.CreateDataRow(dataRow));
								return result;
							}
						);
						global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", false,
							async disposalTracker => {
								var attr = new global::Xunit.v3.DataAttributeRegistration() { DisableParallelization = true, Skip = "Maybe?", SkipWhen = () => global::OtherClass.AlwaysFalse, TestDisplayName = "hey" };
								var result = new global::System.Collections.Generic.List<global::Xunit.ITheoryDataRow>();
								var dataRows = await global::OtherClass.PropertyData;
								if (dataRows == null)
									throw new global::Xunit.Sdk.TestPipelineException("Test data returned null for TestClass.TestMethod. Make sure it is statically initialized before this test method is called.");
								foreach (var dataRow in dataRows)
									result.Add(attr.CreateDataRow(dataRow));
								return result;
							}
						);
						global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod", false,
							async disposalTracker => {
								var invalidParameters = new global::System.Collections.Generic.List<(string Type, string Name, string Value)>();
								if (!global::Xunit.Sdk.TypeHelper.TryConvert(42, out int param0))
									invalidParameters.Add(("int", "x", "42"));
								if (invalidParameters.Count != 0)
									throw new global::Xunit.Sdk.TestPipelineException(
										string.Format(
											global::System.Globalization.CultureInfo.CurrentCulture,
											"Member data method 'TestClass.MethodData' had one or more invalid theory data arguments: {0}",
											string.Join(", ", global::System.Linq.Enumerable.Select(invalidParameters, a => $"{a.Type} {a.Name} ({a.Value})"))
										)
									);
								var attr = new global::Xunit.v3.DataAttributeRegistration() { Explicit = true, Label = "hello", Skip = "Always", SkipUnless = () => global::TestClass.AlwaysTrue, Timeout = 42, Traits = new global::System.Collections.Generic.Dictionary<string, global::System.Collections.Generic.IReadOnlyCollection<string>>(global::System.StringComparer.OrdinalIgnoreCase) { ["Foo"] = new global::System.Collections.Generic.HashSet<string> { "Bar" }} };
								var result = new global::System.Collections.Generic.List<global::Xunit.ITheoryDataRow>();
								var dataRows = global::TestClass.MethodData(param0);
								if (dataRows == null)
									throw new global::Xunit.Sdk.TestPipelineException("Test data returned null for TestClass.TestMethod. Make sure it is statically initialized before this test method is called.");
								await foreach (var dataRow in dataRows)
									result.Add(attr.CreateDataRow(dataRow));
								return result;
							}
						);
					}
				}
			}
			""", result);
	}

	[Fact]
	public async ValueTask GenericDataSources()
	{
		var source = /* lang=c#-test */ """
			using System.Collections.Generic;
			using Xunit;

			public abstract class AbstractBase<T1, T2>
			{
				public static IEnumerable<object[]> Foo => new[] { new object[] { 42 } };

				// This does not generate, because the accessor would be "AbstractBase<T1, T2>.Foo" which can't be closed at runtime
				[Theory]
				[MemberData(nameof(Foo))]
				public void TestMethod1(int _) { }

				// This does generate, because the reference is outside the open generic
				[Theory]
				[MemberData(nameof(OtherClass.Bar), MemberType = typeof(OtherClass))]
				public void TestMethod2(int _) { }
			}

			public class TestClass : AbstractBase<int, string>
			{
				// This generate, because the accessor is "TestClass.Foo" despite Foo being in the open generic
				[Theory]
				[MemberData(nameof(Foo))]
				public void TestMethod3(int _) { }
			}

			public class OtherClass {
				public static IEnumerable<object[]> Bar => new[] { new object[] { 2112 } };
			}
			""";

		var result = GenerateSources(source);

		Assert.Collection(
			result,
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.MemberDataAttribute٠AbstractBase٠TestMethod2٠vljdPEXxN]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class MemberDataAttribute٠AbstractBase٠TestMethod2٠vljdPEXxN : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::AbstractBase<,>", "TestMethod2", false,
								async disposalTracker => {
									var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
									var result = new global::System.Collections.Generic.List<global::Xunit.ITheoryDataRow>();
									var dataRows = global::OtherClass.Bar;
									if (dataRows == null)
										throw new global::Xunit.Sdk.TestPipelineException("Test data returned null for AbstractBase<T1, T2>.TestMethod2. Make sure it is statically initialized before this test method is called.");
									foreach (var dataRow in dataRows)
										result.Add(attr.CreateDataRow(dataRow));
									return result;
								}
							);
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.MemberDataAttribute٠TestClass٠TestMethod3٠cJváVvoWQ]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class MemberDataAttribute٠TestClass٠TestMethod3٠cJváVvoWQ : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterTheoryDataRowFactory("global::TestClass", "TestMethod3", false,
								async disposalTracker => {
									var attr = global::Xunit.v3.DataAttributeRegistration.Empty;
									var result = new global::System.Collections.Generic.List<global::Xunit.ITheoryDataRow>();
									var dataRows = global::TestClass.Foo;
									if (dataRows == null)
										throw new global::Xunit.Sdk.TestPipelineException("Test data returned null for TestClass.TestMethod3. Make sure it is statically initialized before this test method is called.");
									foreach (var dataRow in dataRows)
										result.Add(attr.CreateDataRow(dataRow));
									return result;
								}
							);
						}
					}
				}
				""", generated)
		);
	}
}
