using Xunit;
using Xunit.Generators;

public class ParallelizationAttributeGeneratorTests : CoreGeneratorTest<ParallelizationAttributeGenerator>
{
	[Fact]
	public void AcceptanceTest()
	{
		var source = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;
			using PA = Xunit.Sdk.ParallelAlgorithm;

			[assembly: Parallelization(Algorithm = PA.Aggressive, MaxThreads = Constants.ThirtyTwo * 2, Mode = Xunit.Sdk.ParallelMode.All)]

			static class Constants {
				internal const int ThirtyTwo = 32;
			}
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.ParallelizationAttribute٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class ParallelizationAttribute٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterParallelAlgorithm(Xunit.Sdk.ParallelAlgorithm.Aggressive);
						global::Xunit.v3.RegisteredEngineConfig.RegisterParallelMaxThreads(64);
						global::Xunit.v3.RegisteredEngineConfig.RegisterParallelMode(Xunit.Sdk.ParallelMode.All);
					}
				}
			}
			""", result);
	}
}
