using Xunit;
using Xunit.Generators;

public class TestClassGeneratorTests : CoreGeneratorTest<TestClassGenerator>
{
	[Fact]
	public void AcceptanceTest_Fact()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using System;
			using System.Collections.Generic;
			using System.Threading.Tasks;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			public class TestClass {
				// Success cases

				[Fact]
				public void SimpleTestMethod() { }

				[Fact(DisplayName = "display", Explicit = true, Skip = "maybe?", SkipExceptions = [typeof(Exception)], SkipWhen = nameof(AlwaysTrue), Timeout = 42)]
				public Task WithAttributeParams() => Task.CompletedTask;

				[Fact(Skip = "maybe???", SkipUnless = nameof(OtherClass.AlwaysFalse), SkipType = typeof(OtherClass))]
				public ValueTask WithSkipOnOtherType() => default;

				// Failure cases

				[Fact]
				void PrivateMethod() { }

				[Fact]
				[Theory]
				public void TooManyAttributes() { }

				[Fact]
				public void OverloadedMethod() { }

				[Fact]
				public void OverloadedMethod(int _) { }

				[Fact]
				public async void AsyncVoidUnsupported() { await Task.Yield(); }

				[Fact]
				public int UnsupportedReturnType() => 12;

				[Fact]
				public Task<int> UnsupportedTaskReturnType() => Task.FromResult(12);

				[Fact]
				public ValueTask<int> UnsupportedValueTaskReturnType() => new(12);

				public static bool AlwaysTrue => true;

				public class OtherClass {
					public static bool AlwaysFalse => false;
				}
			}

			public class DerivedTestClass : AbstractTestClass { }

			public class DerivedTestClassWithExtraTests : DerivedTestClass {
				[Fact]
				public void ChildTest() { }
			}

			public class WithFixtures(object o, ITestOutputHelper output, string? optional = null) : IClassFixture<object>, IClassFixture<TypeWithMarkerInterface> {
				[Fact]
				public void TestMethod() => output.WriteLine(o.ToString() + (optional ?? "null"));
			}

			[TestCaseOrderer(typeof(MyOrderer))]
			[TestMethodOrderer(typeof(MyOrderer))]
			public class WithOrderers {
				[Fact]
				public void TestMethod() { }
			}

			// Should not be directly generated for, since it's abstract

			public abstract class AbstractTestClass {
				[Fact]
				public void BaseTestMethod() { }
			}

			// Ignored because private

			class PrivateClass {
				[Fact]
				public void TestMethod() { }
			}

			// Ignored because embedded in open generic

			public class GenericOuterType<T> {
				public class TestClass {
					[Fact]
					public void TestMethod() { }
				}
			}

			// Ignored because of ICollectionFixture<>

			public class TestClassWithCollectionFixture : ICollectionFixture<object> {
				[Fact]
				public void TestMethod() { }
			}

			// Ignored because of parameters

			public class TestClassWithParameters {
				[Fact]
				public void TestMethod(int _) { }
			}

			public class MyOrderer : ITestCaseOrderer, ITestMethodOrderer
			{
				public IReadOnlyCollection<TTestCase> OrderTestCases<TTestCase>(IReadOnlyCollection<TTestCase> testCases)
					where TTestCase : notnull, ITestCase =>
						throw new NotImplementedException();
				public IReadOnlyCollection<TTestMethod?> OrderTestMethods<TTestMethod>(IReadOnlyCollection<TTestMethod?> testMethods)
					where TTestMethod : notnull, ITestMethod =>
						throw new NotImplementedException();
			}

			public class TypeWithMarkerInterface : INotifyLifecycle { }
			""";

		var result = GenerateSources(source);

		Assert.Collection(
			result,
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠TestClass٠1sVmPGREF]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠TestClass٠1sVmPGREF : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::TestClass", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::TestClass), ClassFactory = async mappingManager => {
								var instance = new global::TestClass();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "SimpleTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 13 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "SimpleTestMethod", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = async obj => ((global::TestClass)obj!).SimpleTestMethod() });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "WithAttributeParams", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 16 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "WithAttributeParams", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = obj => global::Xunit.Sdk.AsyncUtility.Await(((global::TestClass)obj!).WithAttributeParams()), DisplayName = "display", Explicit = true, SkipExceptions = new global::System.Type[] { typeof(global::System.Exception) }, SkipReason = "maybe?", SkipWhen = () => global::TestClass.AlwaysTrue, Timeout = 42 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "WithSkipOnOtherType", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 19 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "WithSkipOnOtherType", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = obj => global::Xunit.Sdk.AsyncUtility.Await(((global::TestClass)obj!).WithSkipOnOtherType()), SkipReason = "maybe???", SkipUnless = () => global::TestClass.OtherClass.AlwaysFalse });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠DerivedTestClass٠dp2AvrGCZ]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠DerivedTestClass٠dp2AvrGCZ : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::DerivedTestClass", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::DerivedTestClass), ClassFactory = async mappingManager => {
								var instance = new global::DerivedTestClass();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClass", "BaseTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { DeclaredTypeIndex = "global::AbstractTestClass", SourceFilePath = "file0.cs", SourceLineNumber = 78 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClass", "BaseTestMethod", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = async obj => ((global::DerivedTestClass)obj!).BaseTestMethod() });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠DerivedTestClassWithExtraTests٠a5jJyDijG]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠DerivedTestClassWithExtraTests٠a5jJyDijG : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::DerivedTestClassWithExtraTests", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::DerivedTestClassWithExtraTests), ClassFactory = async mappingManager => {
								var instance = new global::DerivedTestClassWithExtraTests();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClassWithExtraTests", "ChildTest", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 59 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClassWithExtraTests", "ChildTest", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = async obj => ((global::DerivedTestClassWithExtraTests)obj!).ChildTest() });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClassWithExtraTests", "BaseTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { DeclaredTypeIndex = "global::AbstractTestClass", SourceFilePath = "file0.cs", SourceLineNumber = 78 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClassWithExtraTests", "BaseTestMethod", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = async obj => ((global::DerivedTestClassWithExtraTests)obj!).BaseTestMethod() });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠WithFixtures٠HKuKáRkcG]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠WithFixtures٠HKuKáRkcG : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::WithFixtures", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::WithFixtures), ClassFactory = async mappingManager => {
								var missingParameters = new global::System.Collections.Generic.List<(string Type, string Name)>();
								var param0 = await mappingManager.TryGetFixtureArgument<object>();
								if (!param0.Success)
									missingParameters.Add(("object", "o"));
								var param1 = await mappingManager.TryGetFixtureArgument<global::Xunit.ITestOutputHelper>();
								if (!param1.Success)
									missingParameters.Add(("Xunit.ITestOutputHelper", "output"));
								var param2 = await mappingManager.TryGetFixtureArgument<string?>();
								if (!param2.Success)
									param2.Result = default(string?);
								if (missingParameters.Count != 0)
									throw new global::Xunit.Sdk.TestPipelineException(
										string.Format(
											global::System.Globalization.CultureInfo.CurrentCulture,
											"Test class 'WithFixtures' had one or more unresolved constructor arguments: {0}",
											string.Join(", ", global::System.Linq.Enumerable.Select(missingParameters, p => $"{p.Type} {p.Name}"))
										)
									);
								var instance = new global::WithFixtures(param0.Result!, param1.Result!, param2.Result!);
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							}, ClassFixtureFactories = new global::System.Collections.Generic.Dictionary<global::System.Type, global::Xunit.v3.FixtureFactory> {
								[typeof(object)] = async (mappingManager, forceCreation) => {
									if (!forceCreation)
										return null;
									var instance = new object();
									return instance;
								}, [typeof(global::TypeWithMarkerInterface)] = async (mappingManager, forceCreation) => {
									var instance = new global::TypeWithMarkerInterface();
									return instance;
								}
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::WithFixtures", "TestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 64 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::WithFixtures", "TestMethod", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = async obj => ((global::WithFixtures)obj!).TestMethod() });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠WithOrderers٠x2HjaU4E5]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠WithOrderers٠x2HjaU4E5 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::WithOrderers", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::WithOrderers), ClassFactory = async mappingManager => {
								var instance = new global::WithOrderers();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							}, TestCaseOrdererFactory = () => new global::MyOrderer(), TestMethodOrdererFactory = () => new global::MyOrderer() });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::WithOrderers", "TestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 71 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::WithOrderers", "TestMethod", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = async obj => ((global::WithOrderers)obj!).TestMethod() });
						}
					}
				}
				""", generated)
			);
	}

	[Fact]
	public void AcceptanceTest_CulturedFact()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using System;
			using System.Collections.Generic;
			using System.Threading.Tasks;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			public class TestClass {
				// Success cases

				[CulturedFact(["en-US"])]
				public void SimpleTestMethod() { }

				[CulturedFact(["en-US"], DisplayName = "display", Explicit = true, Skip = "maybe?", SkipExceptions = [typeof(Exception)], SkipWhen = nameof(AlwaysTrue), Timeout = 42)]
				public Task WithAttributeParams() => Task.CompletedTask;

				[CulturedFact(["en-US"], Skip = "maybe???", SkipUnless = nameof(OtherClass.AlwaysFalse), SkipType = typeof(OtherClass))]
				public ValueTask WithSkipOnOtherType() => default;

				// Failure cases

				[CulturedFact(["en-US"])]
				void PrivateMethod() { }

				[CulturedFact(["en-US"])]
				[Theory]
				public void TooManyAttributes() { }

				[CulturedFact(["en-US"])]
				public void OverloadedMethod() { }

				[CulturedFact(["en-US"])]
				public void OverloadedMethod(int _) { }

				[CulturedFact(["en-US"])]
				public async void AsyncVoidUnsupported() { await Task.Yield(); }

				[CulturedFact(["en-US"])]
				public int UnsupportedReturnType() => 12;

				[CulturedFact(["en-US"])]
				public Task<int> UnsupportedTaskReturnType() => Task.FromResult(12);

				[CulturedFact(["en-US"])]
				public ValueTask<int> UnsupportedValueTaskReturnType() => new(12);

				public static bool AlwaysTrue => true;

				public class OtherClass {
					public static bool AlwaysFalse => false;
				}
			}

			public class DerivedTestClass : AbstractTestClass { }

			public class DerivedTestClassWithExtraTests : DerivedTestClass {
				[CulturedFact(["en-US"])]
				public void ChildTest() { }
			}

			public class WithFixtures(object o, ITestOutputHelper output, string? optional = null) : IClassFixture<object> {
				[CulturedFact(["en-US"])]
				public void TestMethod() => output.WriteLine(o.ToString() + (optional ?? "null"));
			}

			[TestCaseOrderer(typeof(MyOrderer))]
			[TestMethodOrderer(typeof(MyOrderer))]
			public class WithOrderers {
				[CulturedFact(["en-US"])]
				public void TestMethod() { }
			}

			// Should not be directly generated for, since it's abstract

			public abstract class AbstractTestClass {
				[CulturedFact(["en-US"])]
				public void BaseTestMethod() { }
			}

			// Ignored because private

			class PrivateClass {
				[CulturedFact(["en-US"])]
				public void TestMethod() { }
			}

			// Ignored because embedded in open generic

			public class GenericOuterType<T> {
				public class TestClass {
					[CulturedFact(["en-US"])]
					public void TestMethod() { }
				}
			}

			// Ignored because of ICollectionFixture<>

			public class TestClassWithCollectionFixture : ICollectionFixture<object> {
				[CulturedFact(["en-US"])]
				public void TestMethod() { }
			}

			// Ignored because of parameters

			public class TestClassWithParameters {
				[CulturedFact(["en-US"])]
				public void TestMethod(int _) { }
			}

			// Ignored because of lack of cultures

			public class TestWithoutCultures {
				[CulturedFact([])]
				public void TestMethod() { }
			}

			public class MyOrderer : ITestCaseOrderer, ITestMethodOrderer
			{
				public IReadOnlyCollection<TTestCase> OrderTestCases<TTestCase>(IReadOnlyCollection<TTestCase> testCases)
					where TTestCase : notnull, ITestCase =>
						throw new NotImplementedException();
				public IReadOnlyCollection<TTestMethod?> OrderTestMethods<TTestMethod>(IReadOnlyCollection<TTestMethod?> testMethods)
					where TTestMethod : notnull, ITestMethod =>
						throw new NotImplementedException();
			}
			""";

		var result = GenerateSources(source);

		Assert.Collection(
			result,
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠TestClass٠1sVmPGREF]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠TestClass٠1sVmPGREF : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::TestClass", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::TestClass), ClassFactory = async mappingManager => {
								var instance = new global::TestClass();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "SimpleTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 13 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "SimpleTestMethod", new global::Xunit.v3.CulturedFactTestCaseFactory() { Cultures = ["en-US"], MethodInvoker = async obj => ((global::TestClass)obj!).SimpleTestMethod() });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "WithAttributeParams", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 16 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "WithAttributeParams", new global::Xunit.v3.CulturedFactTestCaseFactory() { Cultures = ["en-US"], MethodInvoker = obj => global::Xunit.Sdk.AsyncUtility.Await(((global::TestClass)obj!).WithAttributeParams()), DisplayName = "display", Explicit = true, SkipExceptions = new global::System.Type[] { typeof(global::System.Exception) }, SkipReason = "maybe?", SkipWhen = () => global::TestClass.AlwaysTrue, Timeout = 42 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "WithSkipOnOtherType", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 19 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "WithSkipOnOtherType", new global::Xunit.v3.CulturedFactTestCaseFactory() { Cultures = ["en-US"], MethodInvoker = obj => global::Xunit.Sdk.AsyncUtility.Await(((global::TestClass)obj!).WithSkipOnOtherType()), SkipReason = "maybe???", SkipUnless = () => global::TestClass.OtherClass.AlwaysFalse });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠DerivedTestClass٠Edpkt29uF]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠DerivedTestClass٠Edpkt29uF : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::DerivedTestClass", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::DerivedTestClass), ClassFactory = async mappingManager => {
								var instance = new global::DerivedTestClass();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClass", "BaseTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { DeclaredTypeIndex = "global::AbstractTestClass", SourceFilePath = "file0.cs", SourceLineNumber = 78 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClass", "BaseTestMethod", new global::Xunit.v3.CulturedFactTestCaseFactory() { Cultures = ["en-US"], MethodInvoker = async obj => ((global::DerivedTestClass)obj!).BaseTestMethod() });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠DerivedTestClassWithExtraTests٠m2VTTLg1b]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠DerivedTestClassWithExtraTests٠m2VTTLg1b : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::DerivedTestClassWithExtraTests", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::DerivedTestClassWithExtraTests), ClassFactory = async mappingManager => {
								var instance = new global::DerivedTestClassWithExtraTests();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClassWithExtraTests", "ChildTest", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 59 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClassWithExtraTests", "ChildTest", new global::Xunit.v3.CulturedFactTestCaseFactory() { Cultures = ["en-US"], MethodInvoker = async obj => ((global::DerivedTestClassWithExtraTests)obj!).ChildTest() });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClassWithExtraTests", "BaseTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { DeclaredTypeIndex = "global::AbstractTestClass", SourceFilePath = "file0.cs", SourceLineNumber = 78 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClassWithExtraTests", "BaseTestMethod", new global::Xunit.v3.CulturedFactTestCaseFactory() { Cultures = ["en-US"], MethodInvoker = async obj => ((global::DerivedTestClassWithExtraTests)obj!).BaseTestMethod() });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠WithFixtures٠aEEJt4eJG]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠WithFixtures٠aEEJt4eJG : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::WithFixtures", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::WithFixtures), ClassFactory = async mappingManager => {
								var missingParameters = new global::System.Collections.Generic.List<(string Type, string Name)>();
								var param0 = await mappingManager.TryGetFixtureArgument<object>();
								if (!param0.Success)
									missingParameters.Add(("object", "o"));
								var param1 = await mappingManager.TryGetFixtureArgument<global::Xunit.ITestOutputHelper>();
								if (!param1.Success)
									missingParameters.Add(("Xunit.ITestOutputHelper", "output"));
								var param2 = await mappingManager.TryGetFixtureArgument<string?>();
								if (!param2.Success)
									param2.Result = default(string?);
								if (missingParameters.Count != 0)
									throw new global::Xunit.Sdk.TestPipelineException(
										string.Format(
											global::System.Globalization.CultureInfo.CurrentCulture,
											"Test class 'WithFixtures' had one or more unresolved constructor arguments: {0}",
											string.Join(", ", global::System.Linq.Enumerable.Select(missingParameters, p => $"{p.Type} {p.Name}"))
										)
									);
								var instance = new global::WithFixtures(param0.Result!, param1.Result!, param2.Result!);
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							}, ClassFixtureFactories = new global::System.Collections.Generic.Dictionary<global::System.Type, global::Xunit.v3.FixtureFactory> {
								[typeof(object)] = async (mappingManager, forceCreation) => {
									if (!forceCreation)
										return null;
									var instance = new object();
									return instance;
								}
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::WithFixtures", "TestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 64 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::WithFixtures", "TestMethod", new global::Xunit.v3.CulturedFactTestCaseFactory() { Cultures = ["en-US"], MethodInvoker = async obj => ((global::WithFixtures)obj!).TestMethod() });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠WithOrderers٠duKuhHTMA]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠WithOrderers٠duKuhHTMA : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::WithOrderers", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::WithOrderers), ClassFactory = async mappingManager => {
								var instance = new global::WithOrderers();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							}, TestCaseOrdererFactory = () => new global::MyOrderer(), TestMethodOrdererFactory = () => new global::MyOrderer() });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::WithOrderers", "TestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 71 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::WithOrderers", "TestMethod", new global::Xunit.v3.CulturedFactTestCaseFactory() { Cultures = ["en-US"], MethodInvoker = async obj => ((global::WithOrderers)obj!).TestMethod() });
						}
					}
				}
				""", generated)
			);
	}

	[Fact]
	public void AcceptanceTest_Theory()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using System;
			using System.Collections.Generic;
			using System.Threading.Tasks;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			public class TestClass {
				// Success cases

				[Theory]
				public void SimpleTestMethod(int _) { }

				[Theory(DisplayName = "display", Explicit = true, Skip = "maybe?", SkipExceptions = [typeof(Exception)], SkipWhen = nameof(AlwaysTrue), Timeout = 42)]
				public Task WithAttributeParams(int _1, string? _2 = null) => Task.CompletedTask;

				[Theory(Skip = "maybe???", SkipUnless = nameof(OtherClass.AlwaysFalse), SkipType = typeof(OtherClass))]
				public ValueTask WithSkipOnOtherType([System.Runtime.InteropServices.Optional] int _1, [System.Runtime.InteropServices.Optional] ushort? _2) => default;

				// Failure cases

				[Theory]
				void PrivateMethod() { }

				[Fact]
				[Theory]
				public void TooManyAttributes() { }

				[Theory]
				public void OverloadedMethod() { }

				[Theory]
				public void OverloadedMethod(int _) { }

				[Theory]
				public async void AsyncVoidUnsupported() { await Task.Yield(); }

				[Theory]
				public int UnsupportedReturnType() => 12;

				[Theory]
				public Task<int> UnsupportedTaskReturnType() => Task.FromResult(12);

				[Theory]
				public ValueTask<int> UnsupportedValueTaskReturnType() => new(12);

				public static bool AlwaysTrue => true;

				public class OtherClass {
					public static bool AlwaysFalse => false;
				}
			}

			public class DerivedTestClass : AbstractTestClass { }

			public class DerivedTestClassWithExtraTests : DerivedTestClass {
				[Theory]
				public void ChildTest() { }
			}

			public class WithFixtures(object o, ITestOutputHelper output, string? optional = null) : IClassFixture<object> {
				[Theory]
				public void TestMethod() => output.WriteLine(o.ToString() + (optional ?? "null"));
			}

			[TestCaseOrderer(typeof(MyOrderer))]
			[TestMethodOrderer(typeof(MyOrderer))]
			public class WithOrderers {
				[Theory]
				public void TestMethod() { }
			}

			// Should not be directly generated for, since it's abstract

			public abstract class AbstractTestClass {
				[Theory]
				public void BaseTestMethod() { }
			}

			// Ignored because private

			class PrivateClass {
				[Theory]
				public void TestMethod() { }
			}

			// Ignored because embedded in open generic

			public class GenericOuterType<T> {
				public class TestClass {
					[Theory]
					public void TestMethod() { }
				}
			}

			// Ignored because of ICollectionFixture<>

			public class TestClassWithCollectionFixture : ICollectionFixture<object> {
				[Theory]
				public void TestMethod() { }
			}

			public class MyOrderer : ITestCaseOrderer, ITestMethodOrderer
			{
				public IReadOnlyCollection<TTestCase> OrderTestCases<TTestCase>(IReadOnlyCollection<TTestCase> testCases)
					where TTestCase : notnull, ITestCase =>
						throw new NotImplementedException();
				public IReadOnlyCollection<TTestMethod?> OrderTestMethods<TTestMethod>(IReadOnlyCollection<TTestMethod?> testMethods)
					where TTestMethod : notnull, ITestMethod =>
						throw new NotImplementedException();
			}
			""";

		var result = GenerateSources(source);

		Assert.Collection(
			result,
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠TestClass٠1sVmPGREF]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠TestClass٠1sVmPGREF : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::TestClass", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::TestClass), ClassFactory = async mappingManager => {
								var instance = new global::TestClass();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "SimpleTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 13 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "SimpleTestMethod", new global::Xunit.v3.TheoryTestCaseFactory() { MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									if (data.Length < 1)
										throw new global::Xunit.Sdk.TestPipelineException(
											string.Format(
												global::System.Globalization.CultureInfo.CurrentCulture,
												"The test method expected 1 parameter value, but {0} parameter value{1} {2} provided.",
												data.Length,
												data.Length == 1 ? "" : "s",
												data.Length == 1 ? "was" : "were"
											)
										);
									var invalidArguments = new global::System.Collections.Generic.List<(string Type, string Name, object? Value)>();
									var param0 = data.TryGet<int>(0);
									if (!param0.Success)
										invalidArguments.Add(("int", "_", param0.RawValue));
									if (invalidArguments.Count != 0)
										throw new global::Xunit.Sdk.TestPipelineException(
											string.Format(
												global::System.Globalization.CultureInfo.CurrentCulture,
												"Test method had one or more invalid theory data arguments: {0}",
												string.Join(", ", global::System.Linq.Enumerable.Select(invalidArguments, a => $"{a.Type} {a.Name} ({a.Value ?? "null"})"))
											)
										);
									((global::TestClass)obj!).SimpleTestMethod(param0.Result!);
								};
							}
							, ParameterNames = new string?[] { "_" } });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "WithAttributeParams", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 16 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "WithAttributeParams", new global::Xunit.v3.TheoryTestCaseFactory() { MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									if (data.Length < 1)
										throw new global::Xunit.Sdk.TestPipelineException(
											string.Format(
												global::System.Globalization.CultureInfo.CurrentCulture,
												"The test method expected 1 parameter value, but {0} parameter value{1} {2} provided.",
												data.Length,
												data.Length == 1 ? "" : "s",
												data.Length == 1 ? "was" : "were"
											)
										);
									var invalidArguments = new global::System.Collections.Generic.List<(string Type, string Name, object? Value)>();
									var param0 = data.TryGet<int>(0);
									if (!param0.Success)
										invalidArguments.Add(("int", "_1", param0.RawValue));
									var param1 = data.TryGetNullableClass<string>(1);
									if (!param1.Success)
										param1.Result = (string?)default(string?)!;
									if (invalidArguments.Count != 0)
										throw new global::Xunit.Sdk.TestPipelineException(
											string.Format(
												global::System.Globalization.CultureInfo.CurrentCulture,
												"Test method had one or more invalid theory data arguments: {0}",
												string.Join(", ", global::System.Linq.Enumerable.Select(invalidArguments, a => $"{a.Type} {a.Name} ({a.Value ?? "null"})"))
											)
										);
									await global::Xunit.Sdk.AsyncUtility.Await(((global::TestClass)obj!).WithAttributeParams(param0.Result!, param1.Result!));
								};
							}
							, ParameterNames = new string?[] { "_1", "_2" }, DisplayName = "display", Explicit = true, ParameterDefaultValues = new string?[] { null, "null" }, SkipExceptions = new global::System.Type[] { typeof(global::System.Exception) }, SkipReason = "maybe?", SkipWhen = () => global::TestClass.AlwaysTrue, Timeout = 42 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "WithSkipOnOtherType", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 19 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "WithSkipOnOtherType", new global::Xunit.v3.TheoryTestCaseFactory() { MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									var param0 = data.TryGet<int>(0);
									if (!param0.Success)
										param0.Result = (int)default(int)!;
									var param1 = data.TryGetNullableStruct<ushort>(1);
									if (!param1.Success)
										param1.Result = (ushort?)default(ushort?)!;
									await global::Xunit.Sdk.AsyncUtility.Await(((global::TestClass)obj!).WithSkipOnOtherType(param0.Result!, param1.Result!));
								};
							}
							, ParameterNames = new string?[] { "_1", "_2" }, ParameterDefaultValues = new string?[] { "default(int)", "default(ushort?)" }, SkipReason = "maybe???", SkipUnless = () => global::TestClass.OtherClass.AlwaysFalse });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠DerivedTestClass٠yP1LfERH9]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠DerivedTestClass٠yP1LfERH9 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::DerivedTestClass", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::DerivedTestClass), ClassFactory = async mappingManager => {
								var instance = new global::DerivedTestClass();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClass", "BaseTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { DeclaredTypeIndex = "global::AbstractTestClass", SourceFilePath = "file0.cs", SourceLineNumber = 78 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClass", "BaseTestMethod", new global::Xunit.v3.TheoryTestCaseFactory() { MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									((global::DerivedTestClass)obj!).BaseTestMethod();
								};
							}
							, ParameterNames = new string?[] {  } });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠DerivedTestClassWithExtraTests٠XAKxe0Opm]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠DerivedTestClassWithExtraTests٠XAKxe0Opm : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::DerivedTestClassWithExtraTests", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::DerivedTestClassWithExtraTests), ClassFactory = async mappingManager => {
								var instance = new global::DerivedTestClassWithExtraTests();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClassWithExtraTests", "ChildTest", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 59 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClassWithExtraTests", "ChildTest", new global::Xunit.v3.TheoryTestCaseFactory() { MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									((global::DerivedTestClassWithExtraTests)obj!).ChildTest();
								};
							}
							, ParameterNames = new string?[] {  } });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClassWithExtraTests", "BaseTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { DeclaredTypeIndex = "global::AbstractTestClass", SourceFilePath = "file0.cs", SourceLineNumber = 78 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClassWithExtraTests", "BaseTestMethod", new global::Xunit.v3.TheoryTestCaseFactory() { MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									((global::DerivedTestClassWithExtraTests)obj!).BaseTestMethod();
								};
							}
							, ParameterNames = new string?[] {  } });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠WithFixtures٠H8aqULg6n]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠WithFixtures٠H8aqULg6n : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::WithFixtures", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::WithFixtures), ClassFactory = async mappingManager => {
								var missingParameters = new global::System.Collections.Generic.List<(string Type, string Name)>();
								var param0 = await mappingManager.TryGetFixtureArgument<object>();
								if (!param0.Success)
									missingParameters.Add(("object", "o"));
								var param1 = await mappingManager.TryGetFixtureArgument<global::Xunit.ITestOutputHelper>();
								if (!param1.Success)
									missingParameters.Add(("Xunit.ITestOutputHelper", "output"));
								var param2 = await mappingManager.TryGetFixtureArgument<string?>();
								if (!param2.Success)
									param2.Result = default(string?);
								if (missingParameters.Count != 0)
									throw new global::Xunit.Sdk.TestPipelineException(
										string.Format(
											global::System.Globalization.CultureInfo.CurrentCulture,
											"Test class 'WithFixtures' had one or more unresolved constructor arguments: {0}",
											string.Join(", ", global::System.Linq.Enumerable.Select(missingParameters, p => $"{p.Type} {p.Name}"))
										)
									);
								var instance = new global::WithFixtures(param0.Result!, param1.Result!, param2.Result!);
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							}, ClassFixtureFactories = new global::System.Collections.Generic.Dictionary<global::System.Type, global::Xunit.v3.FixtureFactory> {
								[typeof(object)] = async (mappingManager, forceCreation) => {
									if (!forceCreation)
										return null;
									var instance = new object();
									return instance;
								}
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::WithFixtures", "TestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 64 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::WithFixtures", "TestMethod", new global::Xunit.v3.TheoryTestCaseFactory() { MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									((global::WithFixtures)obj!).TestMethod();
								};
							}
							, ParameterNames = new string?[] {  } });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠WithOrderers٠iwQGliHáR]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠WithOrderers٠iwQGliHáR : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::WithOrderers", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::WithOrderers), ClassFactory = async mappingManager => {
								var instance = new global::WithOrderers();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							}, TestCaseOrdererFactory = () => new global::MyOrderer(), TestMethodOrdererFactory = () => new global::MyOrderer() });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::WithOrderers", "TestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 71 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::WithOrderers", "TestMethod", new global::Xunit.v3.TheoryTestCaseFactory() { MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									((global::WithOrderers)obj!).TestMethod();
								};
							}
							, ParameterNames = new string?[] {  } });
						}
					}
				}
				""", generated)
			);
	}

	[Fact]
	public void AcceptanceTest_CulturedTheory()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using System;
			using System.Collections.Generic;
			using System.Threading.Tasks;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			public class TestClass {
				// Success cases

				[CulturedTheory(["en-US"])]
				public void SimpleTestMethod(int _) { }

				[CulturedTheory(["en-US"], DisplayName = "display", Explicit = true, Skip = "maybe?", SkipExceptions = [typeof(Exception)], SkipWhen = nameof(AlwaysTrue), Timeout = 42)]
				public Task WithAttributeParams(int _1, string? _2 = null) => Task.CompletedTask;

				[CulturedTheory(["en-US"], Skip = "maybe???", SkipUnless = nameof(OtherClass.AlwaysFalse), SkipType = typeof(OtherClass))]
				public ValueTask WithSkipOnOtherType([System.Runtime.InteropServices.Optional] int _1, [System.Runtime.InteropServices.Optional] ushort? _2) => default;

				// Failure cases

				[CulturedTheory(["en-US"])]
				void PrivateMethod() { }

				[Fact]
				[CulturedTheory(["en-US"])]
				public void TooManyAttributes() { }

				[CulturedTheory(["en-US"])]
				public void OverloadedMethod() { }

				[CulturedTheory(["en-US"])]
				public void OverloadedMethod(int _) { }

				[CulturedTheory(["en-US"])]
				public async void AsyncVoidUnsupported() { await Task.Yield(); }

				[CulturedTheory(["en-US"])]
				public int UnsupportedReturnType() => 12;

				[CulturedTheory(["en-US"])]
				public Task<int> UnsupportedTaskReturnType() => Task.FromResult(12);

				[CulturedTheory(["en-US"])]
				public ValueTask<int> UnsupportedValueTaskReturnType() => new(12);

				public static bool AlwaysTrue => true;

				public class OtherClass {
					public static bool AlwaysFalse => false;
				}
			}

			public class DerivedTestClass : AbstractTestClass { }

			public class DerivedTestClassWithExtraTests : DerivedTestClass {
				[CulturedTheory(["en-US"])]
				public void ChildTest() { }
			}

			public class WithFixtures(object o, ITestOutputHelper output, string? optional = null) : IClassFixture<object> {
				[CulturedTheory(["en-US"])]
				public void TestMethod() => output.WriteLine(o.ToString() + (optional ?? "null"));
			}

			[TestCaseOrderer(typeof(MyOrderer))]
			[TestMethodOrderer(typeof(MyOrderer))]
			public class WithOrderers {
				[CulturedTheory(["en-US"])]
				public void TestMethod() { }
			}

			// Should not be directly generated for, since it's abstract

			public abstract class AbstractTestClass {
				[CulturedTheory(["en-US"])]
				public void BaseTestMethod() { }
			}

			// Ignored because private

			class PrivateClass {
				[CulturedTheory(["en-US"])]
				public void TestMethod() { }
			}

			// Ignored because embedded in open generic

			public class GenericOuterType<T> {
				public class TestClass {
					[CulturedTheory(["en-US"])]
					public void TestMethod() { }
				}
			}

			// Ignored because of ICollectionFixture<>

			public class TestClassWithCollectionFixture : ICollectionFixture<object> {
				[CulturedTheory(["en-US"])]
				public void TestMethod() { }
			}

			public class MyOrderer : ITestCaseOrderer, ITestMethodOrderer
			{
				public IReadOnlyCollection<TTestCase> OrderTestCases<TTestCase>(IReadOnlyCollection<TTestCase> testCases)
					where TTestCase : notnull, ITestCase =>
						throw new NotImplementedException();
				public IReadOnlyCollection<TTestMethod?> OrderTestMethods<TTestMethod>(IReadOnlyCollection<TTestMethod?> testMethods)
					where TTestMethod : notnull, ITestMethod =>
						throw new NotImplementedException();
			}
			""";

		var result = GenerateSources(source);

		Assert.Collection(
			result,
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠TestClass٠1sVmPGREF]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠TestClass٠1sVmPGREF : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::TestClass", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::TestClass), ClassFactory = async mappingManager => {
								var instance = new global::TestClass();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "SimpleTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 13 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "SimpleTestMethod", new global::Xunit.v3.CulturedTheoryTestCaseFactory() { Cultures = ["en-US"], MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									if (data.Length < 1)
										throw new global::Xunit.Sdk.TestPipelineException(
											string.Format(
												global::System.Globalization.CultureInfo.CurrentCulture,
												"The test method expected 1 parameter value, but {0} parameter value{1} {2} provided.",
												data.Length,
												data.Length == 1 ? "" : "s",
												data.Length == 1 ? "was" : "were"
											)
										);
									var invalidArguments = new global::System.Collections.Generic.List<(string Type, string Name, object? Value)>();
									var param0 = data.TryGet<int>(0);
									if (!param0.Success)
										invalidArguments.Add(("int", "_", param0.RawValue));
									if (invalidArguments.Count != 0)
										throw new global::Xunit.Sdk.TestPipelineException(
											string.Format(
												global::System.Globalization.CultureInfo.CurrentCulture,
												"Test method had one or more invalid theory data arguments: {0}",
												string.Join(", ", global::System.Linq.Enumerable.Select(invalidArguments, a => $"{a.Type} {a.Name} ({a.Value ?? "null"})"))
											)
										);
									((global::TestClass)obj!).SimpleTestMethod(param0.Result!);
								};
							}
							, ParameterNames = new string?[] { "_" } });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "WithAttributeParams", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 16 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "WithAttributeParams", new global::Xunit.v3.CulturedTheoryTestCaseFactory() { Cultures = ["en-US"], MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									if (data.Length < 1)
										throw new global::Xunit.Sdk.TestPipelineException(
											string.Format(
												global::System.Globalization.CultureInfo.CurrentCulture,
												"The test method expected 1 parameter value, but {0} parameter value{1} {2} provided.",
												data.Length,
												data.Length == 1 ? "" : "s",
												data.Length == 1 ? "was" : "were"
											)
										);
									var invalidArguments = new global::System.Collections.Generic.List<(string Type, string Name, object? Value)>();
									var param0 = data.TryGet<int>(0);
									if (!param0.Success)
										invalidArguments.Add(("int", "_1", param0.RawValue));
									var param1 = data.TryGetNullableClass<string>(1);
									if (!param1.Success)
										param1.Result = (string?)default(string?)!;
									if (invalidArguments.Count != 0)
										throw new global::Xunit.Sdk.TestPipelineException(
											string.Format(
												global::System.Globalization.CultureInfo.CurrentCulture,
												"Test method had one or more invalid theory data arguments: {0}",
												string.Join(", ", global::System.Linq.Enumerable.Select(invalidArguments, a => $"{a.Type} {a.Name} ({a.Value ?? "null"})"))
											)
										);
									await global::Xunit.Sdk.AsyncUtility.Await(((global::TestClass)obj!).WithAttributeParams(param0.Result!, param1.Result!));
								};
							}
							, ParameterNames = new string?[] { "_1", "_2" }, DisplayName = "display", Explicit = true, ParameterDefaultValues = new string?[] { null, "null" }, SkipExceptions = new global::System.Type[] { typeof(global::System.Exception) }, SkipReason = "maybe?", SkipWhen = () => global::TestClass.AlwaysTrue, Timeout = 42 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "WithSkipOnOtherType", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 19 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "WithSkipOnOtherType", new global::Xunit.v3.CulturedTheoryTestCaseFactory() { Cultures = ["en-US"], MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									var param0 = data.TryGet<int>(0);
									if (!param0.Success)
										param0.Result = (int)default(int)!;
									var param1 = data.TryGetNullableStruct<ushort>(1);
									if (!param1.Success)
										param1.Result = (ushort?)default(ushort?)!;
									await global::Xunit.Sdk.AsyncUtility.Await(((global::TestClass)obj!).WithSkipOnOtherType(param0.Result!, param1.Result!));
								};
							}
							, ParameterNames = new string?[] { "_1", "_2" }, ParameterDefaultValues = new string?[] { "default(int)", "default(ushort?)" }, SkipReason = "maybe???", SkipUnless = () => global::TestClass.OtherClass.AlwaysFalse });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠DerivedTestClass٠zhUmaW3Rà]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠DerivedTestClass٠zhUmaW3Rà : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::DerivedTestClass", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::DerivedTestClass), ClassFactory = async mappingManager => {
								var instance = new global::DerivedTestClass();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClass", "BaseTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { DeclaredTypeIndex = "global::AbstractTestClass", SourceFilePath = "file0.cs", SourceLineNumber = 78 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClass", "BaseTestMethod", new global::Xunit.v3.CulturedTheoryTestCaseFactory() { Cultures = ["en-US"], MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									((global::DerivedTestClass)obj!).BaseTestMethod();
								};
							}
							, ParameterNames = new string?[] {  } });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠DerivedTestClassWithExtraTests٠2tIB4àRw3]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠DerivedTestClassWithExtraTests٠2tIB4àRw3 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::DerivedTestClassWithExtraTests", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::DerivedTestClassWithExtraTests), ClassFactory = async mappingManager => {
								var instance = new global::DerivedTestClassWithExtraTests();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClassWithExtraTests", "ChildTest", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 59 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClassWithExtraTests", "ChildTest", new global::Xunit.v3.CulturedTheoryTestCaseFactory() { Cultures = ["en-US"], MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									((global::DerivedTestClassWithExtraTests)obj!).ChildTest();
								};
							}
							, ParameterNames = new string?[] {  } });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::DerivedTestClassWithExtraTests", "BaseTestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { DeclaredTypeIndex = "global::AbstractTestClass", SourceFilePath = "file0.cs", SourceLineNumber = 78 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::DerivedTestClassWithExtraTests", "BaseTestMethod", new global::Xunit.v3.CulturedTheoryTestCaseFactory() { Cultures = ["en-US"], MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									((global::DerivedTestClassWithExtraTests)obj!).BaseTestMethod();
								};
							}
							, ParameterNames = new string?[] {  } });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠WithFixtures٠BxGHg7Gk0]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠WithFixtures٠BxGHg7Gk0 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::WithFixtures", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::WithFixtures), ClassFactory = async mappingManager => {
								var missingParameters = new global::System.Collections.Generic.List<(string Type, string Name)>();
								var param0 = await mappingManager.TryGetFixtureArgument<object>();
								if (!param0.Success)
									missingParameters.Add(("object", "o"));
								var param1 = await mappingManager.TryGetFixtureArgument<global::Xunit.ITestOutputHelper>();
								if (!param1.Success)
									missingParameters.Add(("Xunit.ITestOutputHelper", "output"));
								var param2 = await mappingManager.TryGetFixtureArgument<string?>();
								if (!param2.Success)
									param2.Result = default(string?);
								if (missingParameters.Count != 0)
									throw new global::Xunit.Sdk.TestPipelineException(
										string.Format(
											global::System.Globalization.CultureInfo.CurrentCulture,
											"Test class 'WithFixtures' had one or more unresolved constructor arguments: {0}",
											string.Join(", ", global::System.Linq.Enumerable.Select(missingParameters, p => $"{p.Type} {p.Name}"))
										)
									);
								var instance = new global::WithFixtures(param0.Result!, param1.Result!, param2.Result!);
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							}, ClassFixtureFactories = new global::System.Collections.Generic.Dictionary<global::System.Type, global::Xunit.v3.FixtureFactory> {
								[typeof(object)] = async (mappingManager, forceCreation) => {
									if (!forceCreation)
										return null;
									var instance = new object();
									return instance;
								}
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::WithFixtures", "TestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 64 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::WithFixtures", "TestMethod", new global::Xunit.v3.CulturedTheoryTestCaseFactory() { Cultures = ["en-US"], MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									((global::WithFixtures)obj!).TestMethod();
								};
							}
							, ParameterNames = new string?[] {  } });
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠WithOrderers٠fcmCVaop4]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠WithOrderers٠fcmCVaop4 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::WithOrderers", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::WithOrderers), ClassFactory = async mappingManager => {
								var instance = new global::WithOrderers();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							}, TestCaseOrdererFactory = () => new global::MyOrderer(), TestMethodOrdererFactory = () => new global::MyOrderer() });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::WithOrderers", "TestMethod", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 71 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::WithOrderers", "TestMethod", new global::Xunit.v3.CulturedTheoryTestCaseFactory() { Cultures = ["en-US"], MethodInvokerFactory = async dataRow => {
								return async obj => {
									await using var disposalTracker = new global::Xunit.Sdk.DisposalTracker();
									var data = dataRow.GetData();
									disposalTracker.AddRange(data);
									((global::WithOrderers)obj!).TestMethod();
								};
							}
							, ParameterNames = new string?[] {  } });
						}
					}
				}
				""", generated)
			);
	}

	[Fact]
	public void Partials_TestClassRegistrationIsDoubledAndIdentical_TraitsAndTestMethodsAreIndividual()
	{
		var source1 = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[TestCaseOrderer(typeof(DefaultTestCaseOrderer))]
			public partial class TestClass : IClassFixture<object> {
				[Fact]
				[Trait("Method", "File1")]
				public partial void TestMethod1() { }
			}
			""";
		var source2 = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[TestMethodOrderer(typeof(DefaultTestMethodOrderer))]
			public partial class TestClass {
				[Trait("Method", "File2")]
				public partial void TestMethod1();

				[Fact]
				public void TestMethod2() { }
			}
			""";
		var expectedTestClassRegistration = /* lang=c#-test */ """
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::TestClass", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::TestClass), ClassFactory = async mappingManager => {
							var instance = new global::TestClass();
							return new global::Xunit.v3.CoreTestClassCreationResult(instance);
						}, ClassFixtureFactories = new global::System.Collections.Generic.Dictionary<global::System.Type, global::Xunit.v3.FixtureFactory> {
							[typeof(object)] = async (mappingManager, forceCreation) => {
								if (!forceCreation)
									return null;
								var instance = new object();
								return instance;
							}
						}, TestCaseOrdererFactory = () => global::Xunit.v3.DefaultTestCaseOrderer.Instance, TestMethodOrdererFactory = () => global::Xunit.v3.DefaultTestMethodOrderer.Instance });

			""";

		var result = GenerateSources(source1, source2);

		Assert.Collection(
			result,
			generated => Assert.Contains(expectedTestClassRegistration + /* lang=c#-test */ """
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "TestMethod1", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 6 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "TestMethod1", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = async obj => ((global::TestClass)obj!).TestMethod1() });
						}
				""", generated),
			generated => Assert.Contains(expectedTestClassRegistration + /* lang=c#-test */ """
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "TestMethod1", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 6 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "TestMethod1", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = async obj => ((global::TestClass)obj!).TestMethod1() });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::TestClass", "TestMethod2", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file1.cs", SourceLineNumber = 9 });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::TestClass", "TestMethod2", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = async obj => ((global::TestClass)obj!).TestMethod2() });
						}
				""", generated)
		);
	}

	// https://github.com/xunit/xunit/issues/3590
	[Fact]
	public void CrossFileInheritance()
	{
		var source1 = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			public class A
			{
				[Fact]
				[TestCaseOrderer(typeof(DefaultTestCaseOrderer))]
				public void TestA() { }
			}
			""";
		var source2 = /* lang=c#-test */ """
			using Xunit;

			public class B : A;
			""";

		var result = GenerateSources(source1, source2);

		Assert.Collection(
			result,
			generated => Assert.Equal(
				"""
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠A٠uG73qQHC4]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠A٠uG73qQHC4 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::A", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::A), ClassFactory = async mappingManager => {
								var instance = new global::A();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::A", "TestA", new global::Xunit.v3.CodeGenTestMethodRegistration() { SourceFilePath = "file0.cs", SourceLineNumber = 6, TestCaseOrdererFactory = () => global::Xunit.v3.DefaultTestCaseOrderer.Instance });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::A", "TestA", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = async obj => ((global::A)obj!).TestA() });
						}
					}
				}
				""",
				generated),
			generated => Assert.Equal(
				"""
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClass٠B٠kMáydor1U]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TestClass٠B٠kMáydor1U : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClass("global::B", new global::Xunit.v3.CodeGenTestClassRegistration() { Class = typeof(global::B), ClassFactory = async mappingManager => {
								var instance = new global::B();
								return new global::Xunit.v3.CoreTestClassCreationResult(instance);
							} });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethod("global::B", "TestA", new global::Xunit.v3.CodeGenTestMethodRegistration() { DeclaredTypeIndex = "global::A", SourceFilePath = "file0.cs", SourceLineNumber = 6, TestCaseOrdererFactory = () => global::Xunit.v3.DefaultTestCaseOrderer.Instance });
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCaseFactory("global::B", "TestA", new global::Xunit.v3.FactTestCaseFactory() { MethodInvoker = async obj => ((global::B)obj!).TestA() });
						}
					}
				}
				""", generated)
		);
	}
}
