using Xunit;
using Xunit.Generators;

public class TestFrameworkAttributeOfTGeneratorTests : CoreGeneratorTest<TestFrameworkAttributeOfTGenerator>
{
	[Fact]
	public void SuccessCase_WithStringCtor()
	{
		var source = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[assembly: TestFramework<CodeGenTestFramework>]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestFrameworkAttributeOfT٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TestFrameworkAttributeOfT٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterTestFrameworkFactory(configFileName => new global::Xunit.v3.CodeGenTestFramework(configFileName));
					}
				}
			}
			""", result);
	}

	[Fact]
	public void SuccessCase_WithParameterlessCtor()
	{
		var source = /* lang=c#-test */ """
			using System;
			using System.Reflection;
			using Xunit;
			using Xunit.v3;

			[assembly: TestFramework<MyTestFramework>]

			public class MyTestFramework : ITestFramework
			{
				public string TestFrameworkDisplayName => "MyTestFramework";

				public ITestFrameworkDiscoverer GetDiscoverer(Assembly assembly) => throw new NotImplementedException();
				public ITestFrameworkExecutor GetExecutor(Assembly assembly) => throw new NotImplementedException();
				public void SetTestPipelineStartup(ITestPipelineStartup pipelineStartup) => throw new NotImplementedException();
			}
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestFrameworkAttributeOfT٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TestFrameworkAttributeOfT٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterTestFrameworkFactory(configFileName => new global::MyTestFramework());
					}
				}
			}
			""", result);
	}

	[Fact]
	public void MissingMatchingCtor()
	{
		var source = /* lang=c#-test */ """
			using System;
			using System.Reflection;
			using Xunit;
			using Xunit.v3;

			[assembly: TestFramework<MyTestFramework>]

			public class MyTestFramework(int x) : ITestFramework
			{
				public string TestFrameworkDisplayName => $"MyTestFramework version {x}";

				public ITestFrameworkDiscoverer GetDiscoverer(Assembly assembly) => throw new NotImplementedException();
				public ITestFrameworkExecutor GetExecutor(Assembly assembly) => throw new NotImplementedException();
				public void SetTestPipelineStartup(ITestPipelineStartup pipelineStartup) => throw new NotImplementedException();
			}
			""";

		var result = GenerateSources(source);

		Assert.Empty(result);
	}
}
