using Xunit;
using Xunit.Generators;

public class TestCaseOrdererAttributeOfTGeneratorTests : CoreGeneratorTest<TestCaseOrdererAttributeOfTGenerator>
{
	[Fact]
	public void SuccessCase_Instance()
	{
		var source = /* lang=c#-test */ """
			using System;
			using System.Collections.Generic;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			[assembly: TestCaseOrderer<MyOrderer>]

			public class MyOrderer : ITestCaseOrderer
			{
				public IReadOnlyCollection<TTestCase> OrderTestCases<TTestCase>(IReadOnlyCollection<TTestCase> testCases)
					where TTestCase : notnull, ITestCase =>
						throw new NotImplementedException();
			}
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestCaseOrdererAttributeOfT٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TestCaseOrdererAttributeOfT٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTestCaseOrdererFactory(() => new global::MyOrderer());
					}
				}
			}
			""", result);
	}

	[Fact]
	public void SuccessCase_Static()
	{
		var source = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[assembly: TestCaseOrderer<UnorderedTestCaseOrderer>]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestCaseOrdererAttributeOfT٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TestCaseOrdererAttributeOfT٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTestCaseOrdererFactory(() => global::Xunit.v3.UnorderedTestCaseOrderer.Instance);
					}
				}
			}
			""", result);
	}

	[Fact]
	public void MissingParameterlessConstructor()
	{
		var source = /* lang=c#-test */ """
			using System;
			using System.Collections.Generic;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			[assembly: TestCaseOrderer<MyOrderer>]

			public class MyOrderer(int x) : ITestCaseOrderer
			{
				public IReadOnlyCollection<TTestCase> OrderTestCases<TTestCase>(IReadOnlyCollection<TTestCase> testCases)
					where TTestCase : notnull, ITestCase =>
						throw new NotImplementedException(x.ToString());
			}
			""";

		var result = GenerateSources(source);

		Assert.Empty(result);
	}
}
