using Xunit;
using Xunit.Generators;

public class TestCollectionOrdererAttributeGeneratorTests : CoreGeneratorTest<TestCollectionOrdererAttributeGenerator>
{
	[Fact]
	public void SuccessCase_Instance()
	{
		var source = /* lang=c#-test */ """
			using System;
			using System.Collections.Generic;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			[assembly: TestCollectionOrderer(typeof(MyOrderer))]

			public class MyOrderer : ITestCollectionOrderer
			{
				public IReadOnlyCollection<TTestCollection> OrderTestCollections<TTestCollection>(IReadOnlyCollection<TTestCollection> testCollections)
					where TTestCollection : ITestCollection =>
						throw new NotImplementedException();
			}
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestCollectionOrdererAttribute٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TestCollectionOrdererAttribute٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTestCollectionOrdererFactory(() => new global::MyOrderer());
					}
				}
			}
			""", result);
	}

	[Fact]
	public void SuccessCase_Static()
	{
		var source = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[assembly: TestCollectionOrderer(typeof(UnorderedTestCollectionOrderer))]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestCollectionOrdererAttribute٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TestCollectionOrdererAttribute٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTestCollectionOrdererFactory(() => global::Xunit.v3.UnorderedTestCollectionOrderer.Instance);
					}
				}
			}
			""", result);
	}

	[Fact]
	public void MissingParameterlessConstructor()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using System;
			using System.Collections.Generic;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			[assembly: TestCollectionOrderer(typeof(MyOrderer))]

			public class MyOrderer(int x) : ITestCollectionOrderer
			{
				public IReadOnlyCollection<TTestCollection> OrderTestCollections<TTestCollection>(IReadOnlyCollection<TTestCollection> testCollections)
					where TTestCollection : ITestCollection =>
						throw new NotImplementedException(x.ToString());
			}
			""";

		var result = GenerateSources(source);

		Assert.Empty(result);
	}

	[Fact]
	public void MissingInterface()
	{
		var source = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[assembly: TestCollectionOrderer(typeof(object))]
			""";

		var result = GenerateSources(source);

		Assert.Empty(result);
	}
}
