using Xunit;
using Xunit.Generators;

public class TestPipelineStartupAttributeGeneratorTests : CoreGeneratorTest<TestPipelineStartupAttributeGenerator>
{
	[Fact]
	public void SuccessCase()
	{
		var source = /* lang=c#-test */ """
			using System;
			using System.Threading.Tasks;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			[assembly: TestPipelineStartup(typeof(MyStartup))]

			public class MyStartup : ITestPipelineStartup
			{
				public ValueTask StartAsync(IMessageSink diagnosticMessageSink) => throw new NotImplementedException();
				public ValueTask StopAsync() => throw new NotImplementedException();
			}
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestPipelineStartupAttribute٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TestPipelineStartupAttribute٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterTestPipelineStartupFactory(() => new global::MyStartup());
					}
				}
			}
			""", result);
	}

	[Fact]
	public void MissingParameterlessCtor()
	{
		var source = /* lang=c#-test */ """
			using System;
			using System.Threading.Tasks;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			[assembly: TestPipelineStartup(typeof(MyStartup))]

			public class MyStartup(int x) : ITestPipelineStartup
			{
				public ValueTask StartAsync(IMessageSink diagnosticMessageSink) => throw new NotImplementedException();
				public ValueTask StopAsync() => throw new NotImplementedException(x.ToString());
			}
			""";

		var result = GenerateSources(source);

		Assert.Empty(result);
	}

	[Fact]
	public void MissingInterface()
	{
		var source = /* lang=c#-test */ """
			using Xunit.v3;

			[assembly: TestPipelineStartup(typeof(object))]
			""";

		var result = GenerateSources(source);

		Assert.Empty(result);
	}
}
