using Xunit;
using Xunit.Generators;

public class TestClassOrdererAttributeOfTGeneratorTests : CoreGeneratorTest<TestClassOrdererAttributeOfTGenerator>
{
	[Fact]
	public void SuccessCase_Instance()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using System;
			using System.Collections.Generic;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			[assembly: TestClassOrderer<MyOrderer>]

			public class MyOrderer : ITestClassOrderer
			{
				public IReadOnlyCollection<TTestClass?> OrderTestClasses<TTestClass>(IReadOnlyCollection<TTestClass?> testClasses)
					where TTestClass : notnull, ITestClass =>
						throw new NotImplementedException();
			}
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClassOrdererAttributeOfT٠I8h9àp87j]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TestClassOrdererAttributeOfT٠I8h9àp87j : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTestClassOrdererFactory(() => new global::MyOrderer());
					}
				}
			}
			""", result);
	}

	[Fact]
	public void SuccessCase_Static()
	{
		var source = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[assembly: TestClassOrderer<UnorderedTestClassOrderer>]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestClassOrdererAttributeOfT٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TestClassOrdererAttributeOfT٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTestClassOrdererFactory(() => global::Xunit.v3.UnorderedTestClassOrderer.Instance);
					}
				}
			}
			""", result);
	}

	[Fact]
	public void MissingParameterlessConstructor()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using System;
			using System.Collections.Generic;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			[assembly: TestClassOrderer<MyOrderer>]

			public class MyOrderer(int x) : ITestClassOrderer
			{
				public IReadOnlyCollection<TTestClass?> OrderTestClasses<TTestClass>(IReadOnlyCollection<TTestClass?> testClasses)
					where TTestClass : notnull, ITestClass =>
						throw new NotImplementedException(x.ToString());
			}
			""";

		var result = GenerateSources(source);

		Assert.Empty(result);
	}
}
