using Xunit;
using Xunit.Generators;

public class TestMethodOrdererAttributeGeneratorTests : CoreGeneratorTest<TestMethodOrdererAttributeGenerator>
{
	[Fact]
	public void SuccessCase_Instance()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using System;
			using System.Collections.Generic;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			[assembly: TestMethodOrderer(typeof(MyOrderer))]

			public class MyOrderer : ITestMethodOrderer
			{
				public IReadOnlyCollection<TTestMethod?> OrderTestMethods<TTestMethod>(IReadOnlyCollection<TTestMethod?> testMethods)
					where TTestMethod : notnull, ITestMethod =>
						throw new NotImplementedException();
			}
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestMethodOrdererAttribute٠I8h9àp87j]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TestMethodOrdererAttribute٠I8h9àp87j : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTestMethodOrdererFactory(() => new global::MyOrderer());
					}
				}
			}
			""", result);
	}

	[Fact]
	public void SuccessCase_Static()
	{
		var source = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[assembly: TestMethodOrderer(typeof(UnorderedTestMethodOrderer))]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TestMethodOrdererAttribute٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TestMethodOrdererAttribute٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTestMethodOrdererFactory(() => global::Xunit.v3.UnorderedTestMethodOrderer.Instance);
					}
				}
			}
			""", result);
	}

	[Fact]
	public void MissingParameterlessConstructor()
	{
		var source = /* lang=c#-test */ """
			#nullable enable

			using System;
			using System.Collections.Generic;
			using Xunit;
			using Xunit.Sdk;
			using Xunit.v3;

			[assembly: TestMethodOrderer(typeof(MyOrderer))]

			public class MyOrderer(int x) : ITestMethodOrderer
			{
				public IReadOnlyCollection<TTestMethod?> OrderTestMethods<TTestMethod>(IReadOnlyCollection<TTestMethod?> testMethods)
					where TTestMethod : notnull, ITestMethod =>
						throw new NotImplementedException(x.ToString());
			}
			""";

		var result = GenerateSources(source);

		Assert.Empty(result);
	}

	[Fact]
	public void MissingInterface()
	{
		var source = /* lang=c#-test */ """
			using Xunit;
			using Xunit.v3;

			[assembly: TestMethodOrderer(typeof(object))]
			""";

		var result = GenerateSources(source);

		Assert.Empty(result);
	}
}
