using Xunit;
using Xunit.Generators;

public class TraitAttributeGeneratorTests : CoreGeneratorTest<TraitAttributeGenerator>
{
	[Fact]
	public void AcceptanceTest()
	{
		var source = /* lang=c#-test */ """
			using Xunit;

			[assembly: Trait("foo", "bar")]
			[assembly: Trait("foo", "baz")]
			[assembly: Trait("biff", "bang")]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TraitAttribute٠PFácoInw4]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class TraitAttribute٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTrait("foo", "bar", "baz");
						global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTrait("biff", "bang");
					}
				}
			}
			""", result);
	}
}
