using Xunit;
using Xunit.Generators;

public class TraitAttributeGeneratorTests : CoreGeneratorTest<TraitAttributeGenerator>
{
	[Fact]
	public void AcceptanceTest()
	{
		var source = /* lang=c#-test */ """
			using Xunit;

			[assembly: Trait("foo", "bar")]
			[assembly: Trait("foo", "baz")]
			[assembly: Trait("biff", "bang")]

			[CollectionDefinition]
			[Trait("foo", "bar")]
			[Trait("foo", "baz")]
			[Trait("biff", "bang")]
			public class TypedCollection { }

			[CollectionDefinition("My collection")]
			[Trait("foo", "bar")]
			[Trait("foo", "baz")]
			[Trait("biff", "bang")]
			public class NamedCollection { }

			[Trait("foo", "bar-Class")]
			[Trait("foo", "baz-Class")]
			[Trait("biff", "bang-Class")]
			public class TestClass {
				[Fact]
				[Trait("foo", "bar-Method")]
				[Trait("foo", "baz-Method")]
				[Trait("biff", "bang-Method")]
				public void TestMethod() { }
			}
			""";

		var sources = GenerateSources(source);

		Assert.Collection(
			sources,
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TraitAttribute٠PFácoInw4]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TraitAttribute٠PFácoInw4 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTrait("foo", "bar", "baz");
							global::Xunit.v3.RegisteredEngineConfig.RegisterAssemblyTrait("biff", "bang");
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TraitAttribute٠AáKuyM0x8]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TraitAttribute٠AáKuyM0x8 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCollectionTrait(null, typeof(global::TypedCollection), "foo", "bar", "baz");
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCollectionTrait(null, typeof(global::TypedCollection), "biff", "bang");
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TraitAttribute٠ZxKXUSQzM]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TraitAttribute٠ZxKXUSQzM : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCollectionTrait("My collection", typeof(global::NamedCollection), "foo", "bar", "baz");
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCollectionTrait("My collection", typeof(global::NamedCollection), "biff", "bang");
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TraitAttribute٠kx8oCcjgE]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TraitAttribute٠kx8oCcjgE : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClassTrait("global::TestClass", "foo", "bar-Class", "baz-Class");
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestClassTrait("global::TestClass", "biff", "bang-Class");
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TraitAttribute٠4áSFuXLO5]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TraitAttribute٠4áSFuXLO5 : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethodTrait("global::TestClass", "TestMethod", "foo", "bar-Method", "baz-Method");
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestMethodTrait("global::TestClass", "TestMethod", "biff", "bang-Method");
						}
					}
				}
				""", generated)
		);
	}

	[Fact]
	public void Partials()
	{
		var source1 = /* lang=c#-test */ """
			using Xunit;

			[Trait("Location", "File1")]
			[CollectionDefinition("foo")]
			public partial class CollectionDefinition { }
			""";
		var source2 = /* lang=c#-test */ """
			using Xunit;

			[Trait("Location", "File2")]
			partial class CollectionDefinition { }
			""";

		var sources = GenerateSources(source1, source2);

		Assert.Collection(
			sources,
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TraitAttribute٠ozyW2àUUQ]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TraitAttribute٠ozyW2àUUQ : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCollectionTrait("foo", typeof(global::CollectionDefinition), "Location", "File1");
						}
					}
				}
				""", generated),
			generated => Assert.Equal(/* lang=c#-test */ """
				// <auto-generated> This file has been auto generated by xunit.v3.core.aot.generators. </auto-generated>

				#nullable enable

				[assembly: global::Xunit.AutoGenerated._47DEQpj8H.TraitAttribute٠kMáydor1U]

				namespace Xunit.AutoGenerated._47DEQpj8H {
					[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
					internal sealed class TraitAttribute٠kMáydor1U : global::Xunit.v3.EngineInitializationAttribute {
						public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
							global::Xunit.v3.RegisteredEngineConfig.RegisterCodeGenTestCollectionTrait("foo", typeof(global::CollectionDefinition), "Location", "File2");
						}
					}
				}
				""", generated)
		);
	}
}
