using Xunit;
using Xunit.Generators;

public class RegisterResultWriterAttributeOfTGeneratorTests : RunnerCommonGeneratorTest<RegisterResultWriterAttributeOfTGenerator>
{
	[Fact]
	public void SingleRegistration()
	{
		var source = /* lang=c#-test */ """
			using Xunit.Runner.Common;

			[assembly: RegisterResultWriter<XmlV2ResultWriter>("foo")]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.runner.common.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.RegisterResultWriterAttributeOfT٠GeiTSPKp1]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class RegisterResultWriterAttributeOfT٠GeiTSPKp1 : global::Xunit.Runner.Common.RunnerInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						{
							var writer = new Xunit.Runner.Common.XmlV2ResultWriter();
							global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterConsoleResultWriter("foo", writer);
							global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterMicrosoftTestingPlatformResultWriter("foo", writer);
						}
					}
				}
			}
			""", result);
	}

	[Fact]
	public void DoubleRegistration()
	{
		var source = /* lang=c#-test */ """
			using Xunit.Runner.Common;

			[assembly: RegisterResultWriter<XmlV2ResultWriter>("foo")]
			[assembly: RegisterResultWriter<XmlV2ResultWriter>("bar")]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.runner.common.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.RegisterResultWriterAttributeOfT٠GeiTSPKp1]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class RegisterResultWriterAttributeOfT٠GeiTSPKp1 : global::Xunit.Runner.Common.RunnerInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						{
							var writer = new Xunit.Runner.Common.XmlV2ResultWriter();
							global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterConsoleResultWriter("foo", writer);
							global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterMicrosoftTestingPlatformResultWriter("foo", writer);
						}
						{
							var writer = new Xunit.Runner.Common.XmlV2ResultWriter();
							global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterConsoleResultWriter("bar", writer);
							global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterMicrosoftTestingPlatformResultWriter("bar", writer);
						}
					}
				}
			}
			""", result);
	}
}
