using Xunit;
using Xunit.Generators;

public class RegisterConsoleResultWriterAttributeGeneratorTests : RunnerCommonGeneratorTest<RegisterConsoleResultWriterAttributeGenerator>
{
	[Fact]
	public void TypeMissingInterface()
	{
		var source = /* lang=c#-test */ """
			using Xunit.Runner.Common;

			[assembly: RegisterConsoleResultWriter("foo", typeof(object))]
			""";

		var result = Generate(source);

		Assert.Empty(result.GeneratedSources);
	}

	[Fact]
	public void SingleRegistration()
	{
		var source = /* lang=c#-test */ """
			using Xunit.Runner.Common;

			[assembly: RegisterConsoleResultWriter("foo", typeof(XmlV2ResultWriter))]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.runner.common.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.RegisterConsoleResultWriterAttribute٠GeiTSPKp1]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class RegisterConsoleResultWriterAttribute٠GeiTSPKp1 : global::Xunit.Runner.Common.RunnerInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterConsoleResultWriter("foo", new Xunit.Runner.Common.XmlV2ResultWriter());
					}
				}
			}
			""", result);
	}

	[Fact]
	public void DoubleRegistration()
	{
		var source = /* lang=c#-test */ """
			using Xunit.Runner.Common;

			[assembly: RegisterConsoleResultWriter("foo", typeof(XmlV2ResultWriter))]
			[assembly: RegisterConsoleResultWriter("bar", typeof(XmlV2ResultWriter))]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal<object>(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.runner.common.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.RegisterConsoleResultWriterAttribute٠GeiTSPKp1]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class RegisterConsoleResultWriterAttribute٠GeiTSPKp1 : global::Xunit.Runner.Common.RunnerInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterConsoleResultWriter("foo", new Xunit.Runner.Common.XmlV2ResultWriter());
						global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterConsoleResultWriter("bar", new Xunit.Runner.Common.XmlV2ResultWriter());
					}
				}
			}
			""", result);
	}
}
