using Xunit;
using Xunit.Generators;

public class RegisterRunnerReporterAttributeOfTGeneratorTests : RunnerCommonGeneratorTest<RegisterRunnerReporterAttributeOfTGenerator>
{
	[Fact]
	public void SingleRegistration()
	{
		var source = /* lang=c#-test */ """
			using Xunit.Runner.Common;

			[assembly: RegisterRunnerReporter<DefaultRunnerReporter>]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.runner.common.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.RegisterRunnerReporterAttributeOfT٠GeiTSPKp1]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class RegisterRunnerReporterAttributeOfT٠GeiTSPKp1 : global::Xunit.Runner.Common.RunnerInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterRunnerReporter(new Xunit.Runner.Common.DefaultRunnerReporter());
					}
				}
			}
			""", result);
	}

	[Fact]
	public void DoubleRegistration()
	{
		var source = /* lang=c#-test */ """
			using Xunit.Runner.Common;

			[assembly: RegisterRunnerReporter<DefaultRunnerReporter>]
			[assembly: RegisterRunnerReporter<SilentReporter>]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.runner.common.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.RegisterRunnerReporterAttributeOfT٠GeiTSPKp1]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class RegisterRunnerReporterAttributeOfT٠GeiTSPKp1 : global::Xunit.Runner.Common.RunnerInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterRunnerReporter(new Xunit.Runner.Common.DefaultRunnerReporter());
						global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterRunnerReporter(new Xunit.Runner.Common.SilentReporter());
					}
				}
			}
			""", result);
	}
}
