using Xunit;
using Xunit.Generators;

public class RegisterMicrosoftTestingPlatformResultWriterAttributeOfTGeneratorTests : RunnerCommonGeneratorTest<RegisterMicrosoftTestingPlatformResultWriterAttributeOfTGenerator>
{
	[Fact]
	public void SingleRegistration()
	{
		var source = /* lang=c#-test */ """
			using Xunit.Runner.Common;

			[assembly: RegisterMicrosoftTestingPlatformResultWriter<XmlV2ResultWriter>("foo")]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.runner.common.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.RegisterMicrosoftTestingPlatformResultWriterAttributeOfT٠GeiTSPKp1]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class RegisterMicrosoftTestingPlatformResultWriterAttributeOfT٠GeiTSPKp1 : global::Xunit.Runner.Common.RunnerInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterMicrosoftTestingPlatformResultWriter("foo", new Xunit.Runner.Common.XmlV2ResultWriter());
					}
				}
			}
			""", result);
	}

	[Fact]
	public void DoubleRegistration()
	{
		var source = /* lang=c#-test */ """
			using Xunit.Runner.Common;

			[assembly: RegisterMicrosoftTestingPlatformResultWriter<XmlV2ResultWriter>("foo")]
			[assembly: RegisterMicrosoftTestingPlatformResultWriter<XmlV2ResultWriter>("bar")]
			""";

		var result = GenerateSingleSource(source);

		Assert.Equal(/* lang=c#-test */ """
			// <auto-generated> This file has been auto generated by xunit.v3.runner.common.aot.generators. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._47DEQpj8H.RegisterMicrosoftTestingPlatformResultWriterAttributeOfT٠GeiTSPKp1]

			namespace Xunit.AutoGenerated._47DEQpj8H {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal sealed class RegisterMicrosoftTestingPlatformResultWriterAttributeOfT٠GeiTSPKp1 : global::Xunit.Runner.Common.RunnerInitializationAttribute {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterMicrosoftTestingPlatformResultWriter("foo", new Xunit.Runner.Common.XmlV2ResultWriter());
						global::Xunit.Runner.Common.RegisteredRunnerConfig.RegisterMicrosoftTestingPlatformResultWriter("bar", new Xunit.Runner.Common.XmlV2ResultWriter());
					}
				}
			}
			""", result);
	}
}
