using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Xunit.Generators;

public abstract class XunitGenerator : IIncrementalGenerator
{
#if XUNIT_GENERATOR_CORE
	const string AssemblyName = "xunit.v3.core.aot.generators";
	const string BaseInitAttributeName = "global::Xunit.v3.EngineInitializationAttribute";
#elif XUNIT_GENERATOR_RUNNERCOMMON
	const string AssemblyName = "xunit.v3.runner.common.aot.generators";
	const string BaseInitAttributeName = "global::Xunit.Runner.Common.RunnerInitializationAttribute";
#else
#error Unknown generator assembly
#endif

	readonly string attributeNameBase;

	protected XunitGenerator()
	{
		attributeNameBase = GetType().Name;
		if (attributeNameBase.EndsWith("Generator", StringComparison.Ordinal))
			attributeNameBase = attributeNameBase.Substring(0, attributeNameBase.Length - 9);
	}

	protected void AddInitAttribute(
		SourceProductionContext context,
		XunitGeneratorResult result,
		string initialization)
	{
		if (result is null)
			return;

		var initAttributeName = $"{attributeNameBase}٠{result.SafeNameSuffix}";
		var namespaceSuffix = result.ProjectPath.ToCompilerSafeName();
		var source = $$"""
			// <auto-generated> This file has been auto generated by {{AssemblyName}}. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._{{namespaceSuffix}}.{{initAttributeName}}]

			namespace Xunit.AutoGenerated._{{namespaceSuffix}} {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal class {{initAttributeName}} : {{BaseInitAttributeName}} {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						{{initialization}}
					}
				}
			}
			""";

		context.AddSource($"{initAttributeName}.g.cs", SourceText.From(source, Encoding.UTF8));
	}

	protected static bool EnsureConstructorParameters(
		INamedTypeSymbol symbol,
		Location? location,
		XunitGeneratorResult result,
		string[] parameterTypes)
	{
		if (symbol is null || result is null || parameterTypes is null)
			return false;

		var ctors =
			symbol
				.Constructors
				.Where(c => !c.IsStatic && c.DeclaredAccessibility == Accessibility.Public && c.Parameters.Length == parameterTypes.Length);

		foreach (var ctor in ctors)
			if (CtorMatches(ctor, parameterTypes))
				return true;

		result.Diagnostics.Add(
			Diagnostic.Create(
				DiagnosticDescriptors.X9000_TypeMustHaveCorrectPublicConstructor,
				location,
				symbol,
				string.Join(", ", parameterTypes)
			)
		);

		return false;

		static bool CtorMatches(
			IMethodSymbol ctor,
			string[] parameterTypes)
		{
			for (var idx = 0; idx < parameterTypes.Length; ++idx)
			{
				var ctorParameter = ctor.Parameters[idx];
				var expectedType = parameterTypes[idx];

				// TODO: Is it worth the time to look up the inheritance hierarchy of the target type?
				// This feels like, on balance, expensive, rather than just doing a strict requirement.
				if (ctorParameter.Type.ToString() != expectedType)
					return false;
			}

			return true;
		}
	}

	protected static bool EnsureImplementsInterface(
		ITypeSymbol symbol,
		Location? location,
		XunitGeneratorResult result,
		string fullyQualifiedInterfaceName)
	{
		if (symbol is null || fullyQualifiedInterfaceName is null || result is null)
			return false;

		if (symbol.Implements(fullyQualifiedInterfaceName))
			return true;

		result.Diagnostics.Add(
			Diagnostic.Create(
				DiagnosticDescriptors.X9001_TypeMustImplementInterface,
				location,
				symbol,
				fullyQualifiedInterfaceName
			)
		);

		return false;
	}

	protected static bool EnsureImplementsInterfaces(
		ITypeSymbol symbol,
		Location? location,
		XunitGeneratorResult result,
		params string[] fullyQualifiedInterfaceNames)
	{
		if (symbol is null || result is null || fullyQualifiedInterfaceNames is null)
			return false;

		if (fullyQualifiedInterfaceNames.Length == 0)
			return true;

		var missingInterfaces = symbol.ImplementsAll(fullyQualifiedInterfaceNames);
		if (missingInterfaces.Count == 0)
			return true;

		foreach (var missingInterface in missingInterfaces)
			result.Diagnostics.Add(
				Diagnostic.Create(
					DiagnosticDescriptors.X9001_TypeMustImplementInterface,
					location,
					symbol,
					missingInterface
				)
			);

		return false;
	}

	protected static bool EnsureParameterlessPublicCtor(
		INamedTypeSymbol symbol,
		Location? location,
		XunitGeneratorResult result,
		[NotNullWhen(true)] out IMethodSymbol? ctor)
	{
		ctor = null;

		if (symbol is null || result is null)
			return false;

		var targetCtor =
			symbol
				.Constructors
				.FirstOrDefault(c => !c.IsStatic && c.DeclaredAccessibility == Accessibility.Public && c.Parameters.All(p => p.IsOptional || p.IsParams));

		if (targetCtor is not null)
		{
			ctor = targetCtor;
			return true;
		}

		result.Diagnostics.Add(
			Diagnostic.Create(
				DiagnosticDescriptors.X9000_TypeMustHaveCorrectPublicConstructor,
				location,
				symbol,
				string.Empty
			)
		);

		return false;
	}

	void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
	{
		var projectPath =
			context
				.AnalyzerConfigOptionsProvider
				.Select((provider, _) => provider.GlobalOptions.TryGetValue("build_property.MSBuildProjectFullPath", out var projectPath) ? projectPath : string.Empty);

		Initialize(context, projectPath);
	}

	protected abstract void Initialize(
		IncrementalGeneratorInitializationContext context,
		IncrementalValueProvider<string> projectPath);
}
