namespace Xunit.Internal;

internal static class XunitEntryPointGenerator
{
	internal static string GetMTPEntryPointCSharp(string @namespace) =>
		$$"""
		// <auto-generated> This file has been auto generated by xunit.v3.msbuildtasks. </auto-generated>

		namespace {{@namespace}}
		{
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal class XunitAutoGeneratedEntryPoint
			{
				public static int Main(string[] args)
				{
					if (global::System.Linq.Enumerable.Any(args, arg => arg == "-automated" || arg == "@@"))
						return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
					else
						return global::Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework.RunAsync(args, SelfRegisteredExtensions.AddSelfRegisteredExtensions).GetAwaiter().GetResult();
				}
			}
		}
		""";

	internal static string GetMTPEntryPointFSharp(string @namespace) =>
		$$"""
		// <auto-generated> This file has been auto generated by xunit.v3.msbuildtasks. </auto-generated>

		module internal {{@namespace}}

		[<EntryPoint>]
		[<global.System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>]
		let main args =
		    if Array.exists(fun arg -> arg = "-automated" || arg = "@@") args then
		        global.Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()
		    else
		        global.Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework.RunAsync(args, System.Action<_,_>(fun b a -> SelfRegisteredExtensions.AddSelfRegisteredExtensions(b,a))).GetAwaiter().GetResult()
		""";

	internal static string GetMTPEntryPointVB() =>
		$$"""
		' <auto-generated> This file has been auto generated by xunit.v3.msbuildtasks. </auto-generated>

		<Global.System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>
		Friend Class XunitAutoGeneratedEntryPoint
			Public Shared Function Main(args As String()) As Integer
				If Global.System.Linq.Enumerable.Any(args, Function(arg) arg = "-automated" OrElse arg = "@@") Then
					Return Global.Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()
				Else
					Return Global.Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework.RunAsync(args, AddressOf SelfRegisteredExtensions.AddSelfRegisteredExtensions).GetAwaiter().GetResult()
				End If
			End Function
		End Class
		""";

	internal static string GetNonMTPEntryPointCSharp(string @namespace) =>
		$$"""
		// <auto-generated> This file has been auto generated by xunit.v3.msbuildtasks. </auto-generated>

		namespace {{@namespace}}
		{
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal class XunitAutoGeneratedEntryPoint
			{
				public static int Main(string[] args)
				{
					return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
				}
			}
		}
		""";

	internal static string GetNonMTPEntryPointFSharp(string @namespace) =>
		$$"""
		// <auto-generated> This file has been auto generated by xunit.v3.msbuildtasks. </auto-generated>

		module internal {{@namespace}}

		[<EntryPoint>]
		[<global.System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>]
		let main args =
		    global.Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()
		""";

	internal static string GetNonMTPEntryPointVB() =>
		$$"""
		' <auto-generated> This file has been auto generated by xunit.v3.msbuildtasks. </auto-generated>

		<Global.System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>
		Friend Class XunitAutoGeneratedEntryPoint
			Public Shared Function Main(args As String()) As Integer
				Return Global.Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()
			End Function
		End Class
		""";

	// Source generated from this function should be kept in sync with $/src/common.tests/EntryPoint.cs
	internal static string GetXunitEntryPointCSharp(string @namespace) =>
		$$"""
		// <auto-generated> This file has been auto generated by xunit.v3.msbuildtasks. </auto-generated>

		namespace {{@namespace}}
		{
			[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
			internal class XunitAutoGeneratedEntryPoint
			{
				public static int Main(string[] args)
				{
					if (global::System.Linq.Enumerable.Any(args, arg => arg == "--server" || arg == "--internal-msbuild-node"))
						return global::Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework.RunAsync(args, SelfRegisteredExtensions.AddSelfRegisteredExtensions).GetAwaiter().GetResult();
					else
						return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
				}
			}
		}
		""";

	internal static string GetXunitEntryPointFSharp(string @namespace) =>
		$$"""
		// <auto-generated> This file has been auto generated by xunit.v3.msbuildtasks. </auto-generated>

		module internal {{@namespace}}

		[<EntryPoint>]
		[<global.System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>]
		let main args =
		    if Array.exists(fun arg -> arg = "--server" || arg = "--internal-msbuild-node") args then
		        global.Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework.RunAsync(args, System.Action<_,_>(fun b a -> SelfRegisteredExtensions.AddSelfRegisteredExtensions(b,a))).GetAwaiter().GetResult()
		    else
		        global.Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()
		""";

	internal static string GetXunitEntryPointVB() =>
		$$"""
		' <auto-generated> This file has been auto generated by xunit.v3.msbuildtasks. </auto-generated>

		<Global.System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>
		Friend Class XunitAutoGeneratedEntryPoint
			Public Shared Function Main(args As String()) As Integer
				If Global.System.Linq.Enumerable.Any(args, Function(arg) arg = "--server" OrElse arg = "--internal-msbuild-node") Then
					Return Global.Xunit.MicrosoftTestingPlatform.TestPlatformTestFramework.RunAsync(args, AddressOf SelfRegisteredExtensions.AddSelfRegisteredExtensions).GetAwaiter().GetResult()
				Else
					Return Global.Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()
				End If
			End Function
		End Class
		""";
}
