// <auto-generated> This file has been auto generated. </auto-generated>
//
// You can exclude this file from compilation by adding the following to your .csproj file:
//
//   <PropertyGroup>
//     <XunitAutoGeneratedEntryPoint>false</XunitAutoGeneratedEntryPoint>
//   </PropertyGroup>

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public class AutoGeneratedEntryPoint
{
	public static async global::System.Threading.Tasks.Task<int> Main(string[] args)
	{
		return await global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args);
	}
}
