// <auto-generated> This file has been auto generated. </auto-generated>
//
// You can exclude this file from compilation by adding the following to your .fsproj file:
//
//   <PropertyGroup>
//     <XunitAutoGeneratedEntryPoint>false</XunitAutoGeneratedEntryPoint>
//   </PropertyGroup>

module AutoGeneratedEntryPoint

[<EntryPoint>]
[<global.System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>]
let main args =
    global.Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult()
