' <auto-generated> This file has been auto generated. </auto-generated>
'
' You can exclude this file from compilation by adding the following to your .vbproj file:
'
'   <PropertyGroup>
'     <XunitAutoGeneratedEntryPoint>false</XunitAutoGeneratedEntryPoint>
'   </PropertyGroup>

<Global.System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>
Public Class AutoGeneratedEntryPoint
	Public Shared Function Main(args As String()) As Integer
		Return Global.Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args, Nothing, Nothing, Nothing).GetAwaiter().GetResult()
	End Function
End Class
