' <auto-generated> This file has been auto generated. </auto-generated>
'
' You can exclude this file from compilation by adding the following to your .vbproj file:
'
'   <PropertyGroup>
'     <XunitAutoGeneratedEntryPoint>false</XunitAutoGeneratedEntryPoint>
'   </PropertyGroup>

Imports Xunit.Runner.InProc.SystemConsole

Public Class AutoGeneratedEntryPoint
	Public Shared Function Main(args As String()) As Integer
		Return ConsoleRunner.Run(args, Nothing, Nothing, Nothing).GetAwaiter().GetResult()
	End Function
End Class
