' <auto-generated> This file has been auto generated by xunit.v3.core. </auto-generated>

<Assembly: Global.Xunit.Runner.Common.RegisterRunnerReporter(GetType(Global.Xunit.Runner.Common.AppVeyorReporter))>
<Assembly: Global.Xunit.Runner.Common.RegisterRunnerReporter(GetType(Global.Xunit.Runner.Common.DefaultRunnerReporter))>
<Assembly: Global.Xunit.Runner.Common.RegisterRunnerReporter(GetType(Global.Xunit.Runner.Common.JsonReporter))>
<Assembly: Global.Xunit.Runner.Common.RegisterRunnerReporter(GetType(Global.Xunit.Runner.Common.QuietReporter))>
<Assembly: Global.Xunit.Runner.Common.RegisterRunnerReporter(GetType(Global.Xunit.Runner.Common.SilentReporter))>
<Assembly: Global.Xunit.Runner.Common.RegisterRunnerReporter(GetType(Global.Xunit.Runner.Common.TeamCityReporter))>
<Assembly: Global.Xunit.Runner.Common.RegisterRunnerReporter(GetType(Global.Xunit.Runner.Common.VerboseReporter))>
<Assembly: Global.Xunit.Runner.Common.RegisterRunnerReporter(GetType(Global.Xunit.Runner.Common.VstsReporter))>
