// <auto-generated> This file has been auto generated by xunit.v3.core. </auto-generated>

<Assembly: Global.Xunit.Runner.Common.RegisterResultWriter("ctrf", GetType(Global.Xunit.Runner.Common.CtrfResultWriter))]
<Assembly: Global.Xunit.Runner.Common.RegisterResultWriter("html", GetType(Global.Xunit.Runner.Common.HtmlResultWriter))]
<Assembly: Global.Xunit.Runner.Common.RegisterResultWriter("junit", GetType(Global.Xunit.Runner.Common.JUnitResultWriter))]
<Assembly: Global.Xunit.Runner.Common.RegisterResultWriter("nunit", GetType(Global.Xunit.Runner.Common.NUnitResultWriter))]
<Assembly: Global.Xunit.Runner.Common.RegisterResultWriter("trx", GetType(Global.Xunit.Runner.Common.TrxResultWriter))]
<Assembly: Global.Xunit.Runner.Common.RegisterResultWriter("xml", GetType(Global.Xunit.Runner.Common.XunitV2ResultWriter))]
<Assembly: Global.Xunit.Runner.Common.RegisterConsoleResultWriter("xmlV1", GetType(Global.Xunit.Runner.Common.XunitV1ResultWriter))]
