// <auto-generated> This file has been auto generated by xunit.v3.core. </auto-generated>

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public class XunitAutoGeneratedEntryPoint
{
	public static int Main(string[] args)
	{
		if (global::System.Linq.Enumerable.Any(args, arg => arg == "--server" || arg == "--internal-msbuild-node"))
			return global::Xunit.Runner.InProc.SystemConsole.TestingPlatform.TestPlatformTestFramework.RunAsync(args, global::SelfRegisteredExtensions.AddSelfRegisteredExtensions).GetAwaiter().GetResult();
		else
			return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
	}
}
