#nullable enable

using System;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Xunit.Generators
{
	/// <summary>
	/// A base class that can be used for xUnit.net source generators.
	/// </summary>
	public abstract class XunitGenerator : IIncrementalGenerator
	{
		readonly string assemblyName;
		readonly string attributeNameBase;

		/// <summary>
		/// Initializes a new instance of the <see cref="XunitGenerator"/> class.
		/// </summary>
		/// <remarks>
		/// The assembly name used in the "source generated by" banner is pulled from the assembly name
		/// where this type lives. The based name of the generated init attributes is based on this
		/// type's name (with <c>"Generator"</c> removed from the end, if present).
		/// </remarks>
		protected XunitGenerator()
		{
			assemblyName = GetType().Assembly.GetName().Name ?? "<unknown assembly>";

			attributeNameBase = GetType().Name;
			if (attributeNameBase.EndsWith("Generator", StringComparison.Ordinal))
				attributeNameBase = attributeNameBase.Substring(0, attributeNameBase.Length - 9);
		}

		/// <summary>
		/// Gets the base class name for the generated init attribute.
		/// </summary>
		/// <remarks>
		/// By default, returns <c>"global::Xunit.v3.EngineInitializationAttribute"</c> for generating registrations
		/// for <c>xunit.v3.core.aot</c> (for test projects).<br />
		/// <br />
		/// If source is being generated for <c>xunit.v3.runner.common.aot</c>, override this to return
		/// <c>"global::Xunit.Runner.Common.RunnerInitializationAttribute"</c> instead.
		/// </remarks>
		protected virtual string BaseInitAttributeName =>
			"global::Xunit.v3.EngineInitializationAttribute";

		/// <summary>
		/// Generates source for an initialization attribute.
		/// </summary>
		/// <param name="context">The source production context</param>
		/// <param name="result">The generator result</param>
		/// <param name="initializeCode">The lines of code to be placed into <c>InitializeAsync</c></param>
		/// <param name="disposeCode">The optional lines of code to be placed into <c>DisposeAsync</c></param>
		protected void AddInitAttribute(
			SourceProductionContext context,
			XunitGeneratorResult result,
			string initializeCode,
			string? disposeCode = null)
		{
			if (result is null || !result.ShouldGenerate || initializeCode is null)
				return;

			var initAttributeName = $"{attributeNameBase}٠{result.InitAttributeNameSuffix}";
			var cleanupCode =
				disposeCode is null
					? string.Empty
					:
$@"
		public override async global::System.Threading.Tasks.ValueTask DisposeAsync() {{
			{disposeCode.TrimEnd('\n').Replace("\n", "\n\t\t\t")}
		}}";
			var source =
$@"// <auto-generated> This file has been auto generated by {assemblyName}. </auto-generated>

#nullable enable

[assembly: global::{result.GeneratorNamespace}.{initAttributeName}]

namespace {result.GeneratorNamespace} {{
	[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
	internal sealed class {initAttributeName} : {BaseInitAttributeName} {{
		public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {{
			{initializeCode.TrimEnd('\n').Replace("\n", "\n\t\t\t")}
		}}{cleanupCode}
	}}
}}";

			context.AddSource($"{initAttributeName}.g.cs", SourceText.From(source, Encoding.UTF8));
		}

		void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
		{
			var properties =
				context
					.AnalyzerConfigOptionsProvider
					.Select((provider, _) => new XunitMSBuildProperties
					{
						MSBuildProjectFullPath = provider.GlobalOptions.TryGetValue("build_property.MSBuildProjectFullPath", out var projectPath) ? projectPath : null,
						XunitTestProjectAOT = provider.GlobalOptions.TryGetValue("build_property.XunitTestProjectAOT", out var aotFlag) ? aotFlag : null
					});

			Initialize(context, properties);
		}

		/// <summary>
		/// Implement this method to perform initialization and registration of the incremental source generator.
		/// </summary>
		/// <param name="context">The initialization context</param>
		/// <param name="properties">The MSBuild property provider</param>
		protected abstract void Initialize(
			IncrementalGeneratorInitializationContext context,
			IncrementalValueProvider<XunitMSBuildProperties> properties);
	}
}
