#nullable enable

#pragma warning disable IDE0290 // Use primary constructor

using System;
using Microsoft.CodeAnalysis;

namespace Xunit.Generators
{
	/// <summary>
	/// Base type for generator results for <see cref="XunitGenerator"/>.
	/// </summary>
	public class XunitGeneratorResult : IEquatable<XunitGeneratorResult>
	{
		string? generatorNamespace;
		readonly string sourceFilePath;
		readonly int syntaxLocationStart;

		/// <summary>
		/// Initializes a new instance of the <see cref="XunitGeneratorResult"/> class.
		/// </summary>
		/// <param name="sourceFilePath">The source file path of the syntax tree (typically retrieved by
		/// calling <c>context.SemanticModel.SyntaxTree.FilePath</c>)</param>
		/// <param name="syntaxLocation">The location of the syntax node (typically retrieved by
		/// calling <c>context.TargetNode.GetLocation()</c>)</param>
		/// <remarks>The <paramref name="sourceFilePath"/> and <paramref name="syntaxLocation"/> are used to
		/// help construct a unique name for the init attribute.</remarks>
		public XunitGeneratorResult(
			string sourceFilePath,
			Location syntaxLocation)
		{
			this.sourceFilePath = sourceFilePath ?? throw new ArgumentNullException(nameof(sourceFilePath));
			syntaxLocationStart = syntaxLocation?.SourceSpan.Start ?? throw new ArgumentNullException(nameof(syntaxLocation));
		}

		/// <summary>
		/// The namespace to put generated source into.
		/// </summary>
		public string GeneratorNamespace
		{
			get => generatorNamespace ?? throw new InvalidOperationException("Failed to initialize generator result");
			private set => generatorNamespace = value;
		}

		/// <summary>
		/// Used to decorate type names to make them easier to identify in the generated types list
		/// (for example, TestClassGenerator will put the class name into the generated attribute name)
		/// </summary>
		public string GeneratorSuffix { get; set; } = string.Empty;

		/// <summary>
		/// Gets the suffix to the init attribute name, which includes <see cref="GeneratorSuffix"/> plus a compiler
		/// safe name created from the source file and location of the source.
		/// </summary>
		public string InitAttributeNameSuffix =>
			GeneratorSuffix + $"{sourceFilePath}:{syntaxLocationStart}".ToCompilerSafeName();

		/// <summary>
		/// Get a flag which indicates if the result should generate source.
		/// </summary>
		public bool ShouldGenerate { get; private set; }

		/// <inheritdoc/>
		public override bool Equals(object? obj) =>
			Equals(obj as XunitGeneratorResult);

		/// <inheritdoc/>
		public bool Equals(XunitGeneratorResult? other)
		{
			try
			{
				return
					other != null &&
					ComparerHelper.Equal(GeneratorNamespace, other.GeneratorNamespace) &&
					ComparerHelper.Equal(GeneratorSuffix, other.GeneratorSuffix) &&
					ComparerHelper.Equal(InitAttributeNameSuffix, other.InitAttributeNameSuffix);
			}
			catch
			{
				return false;
			}
		}

		/// <summary>
		/// Initializes the generator result with the MSBuild properties.
		/// </summary>
		/// <param name="properties">The MSBuild property values</param>
		/// <remarks>
		/// See the XML doc comments for <see cref="XunitMSBuildProperties"/> for more information on how to ensure
		/// that your soruce generator has access to the required MSBuild properties.
		/// </remarks>
		public void Initialize(XunitMSBuildProperties properties)
		{
			if (properties is null)
				throw new ArgumentNullException(nameof(properties));

			GeneratorNamespace = $"Xunit.AutoGenerated._{(properties.MSBuildProjectFullPath ?? string.Empty).ToCompilerSafeName()}";
			ShouldGenerate = properties.XunitTestProjectAOT != "false";
		}

		/// <inheritdoc/>
		public override int GetHashCode()
		{
			try
			{
				return HashCodeHelper.Start().With(GeneratorNamespace).With(GeneratorSuffix).With(InitAttributeNameSuffix);
			}
			catch
			{
				return 0;
			}
		}
	}
}
